// Code generated by compile-constraints from constant_empty_str.vgo. DO NOT EDIT.
package interactor

import "mazzy/mazarin/vm"

var ProgConstantEmptyStr = &vm.Program{
	Code: []vm.Inst{
		{Opcode: 0x05, Typ: 0x00, Op1: 0, Op2: 0, Flags: 0, Imm: 0x0},
		{Opcode: 0x70, Typ: 0x00, Op1: 0, Op2: 1, Flags: 0, Imm: 0x0},
	},
	Strings: []string{
		"",
	},
	NumArgs: 0,
	ArgTypes: []uint8{},
	Funcs: []vm.FuncInfo{
		{Name: "constant_empty_str", PC: 0, NumArgs: 0, NumLocals: 0, LocalBase: 0},
	},
	Entry: 0,
}
