// Code generated by compile-constraints from identity_point2d.vgo. DO NOT EDIT.
package interactor

import "mazzy/mazarin/vm"

var ProgIdentityPoint2d = &vm.Program{
	Code: []vm.Inst{
		{Opcode: 0x05, Typ: 0x00, Op1: 0, Op2: 0, Flags: 0, Imm: 0x0},
		{Opcode: 0x80, Typ: 0x00, Op1: 206, Op2: 1, Flags: 0, Imm: 0x0},
		{Opcode: 0x70, Typ: 0x00, Op1: 0, Op2: 1, Flags: 0, Imm: 0x0},
	},
	Strings: []string{
		"_0_",
	},
	NumArgs: 0,
	ArgTypes: []uint8{},
	Funcs: []vm.FuncInfo{
		{Name: "identity_point2d", PC: 0, NumArgs: 0, NumLocals: 0, LocalBase: 0},
	},
	Entry: 0,
}
