// Code generated by compile-constraints from offset_point.vgo. DO NOT EDIT.
package interactor

import "mazzy/mazarin/vm"

var ProgOffsetPoint = &vm.Program{
	Code: []vm.Inst{
		{Opcode: 0x05, Typ: 0x00, Op1: 0, Op2: 0, Flags: 0, Imm: 0x0},
		{Opcode: 0x80, Typ: 0x00, Op1: 206, Op2: 1, Flags: 0, Imm: 0x0},
		{Opcode: 0x80, Typ: 0x00, Op1: 112, Op2: 1, Flags: 0, Imm: 0x0},
		{Opcode: 0x11, Typ: 0x00, Op1: 0, Op2: 0, Flags: 0, Imm: 0x0},
		{Opcode: 0x05, Typ: 0x00, Op1: 0, Op2: 0, Flags: 0, Imm: 0x0},
		{Opcode: 0x80, Typ: 0x00, Op1: 206, Op2: 1, Flags: 0, Imm: 0x0},
		{Opcode: 0x80, Typ: 0x00, Op1: 113, Op2: 1, Flags: 0, Imm: 0x0},
		{Opcode: 0x11, Typ: 0x00, Op1: 1, Op2: 0, Flags: 0, Imm: 0x0},
		{Opcode: 0x05, Typ: 0x00, Op1: 1, Op2: 0, Flags: 0, Imm: 0x0},
		{Opcode: 0x80, Typ: 0x00, Op1: 206, Op2: 1, Flags: 0, Imm: 0x0},
		{Opcode: 0x80, Typ: 0x00, Op1: 112, Op2: 1, Flags: 0, Imm: 0x0},
		{Opcode: 0x11, Typ: 0x00, Op1: 2, Op2: 0, Flags: 0, Imm: 0x0},
		{Opcode: 0x05, Typ: 0x00, Op1: 1, Op2: 0, Flags: 0, Imm: 0x0},
		{Opcode: 0x80, Typ: 0x00, Op1: 206, Op2: 1, Flags: 0, Imm: 0x0},
		{Opcode: 0x80, Typ: 0x00, Op1: 113, Op2: 1, Flags: 0, Imm: 0x0},
		{Opcode: 0x11, Typ: 0x00, Op1: 3, Op2: 0, Flags: 0, Imm: 0x0},
		{Opcode: 0x10, Typ: 0x00, Op1: 0, Op2: 0, Flags: 0, Imm: 0x0},
		{Opcode: 0x10, Typ: 0x00, Op1: 2, Op2: 0, Flags: 0, Imm: 0x0},
		{Opcode: 0x20, Typ: 0x01, Op1: 0, Op2: 0, Flags: 0, Imm: 0x0},
		{Opcode: 0x10, Typ: 0x00, Op1: 1, Op2: 0, Flags: 0, Imm: 0x0},
		{Opcode: 0x10, Typ: 0x00, Op1: 3, Op2: 0, Flags: 0, Imm: 0x0},
		{Opcode: 0x20, Typ: 0x01, Op1: 0, Op2: 0, Flags: 0, Imm: 0x0},
		{Opcode: 0x80, Typ: 0x00, Op1: 111, Op2: 2, Flags: 0, Imm: 0x0},
		{Opcode: 0x70, Typ: 0x00, Op1: 0, Op2: 1, Flags: 0, Imm: 0x0},
	},
	Strings: []string{
		"_0_",
		"_1_",
	},
	NumArgs: 0,
	ArgTypes: []uint8{},
	Funcs: []vm.FuncInfo{
		{Name: "offset_point", PC: 0, NumArgs: 0, NumLocals: 4, LocalBase: 0},
	},
	Entry: 0,
}
