// Package compile translates a restricted subset of Go into constraint VM
// bytecode. It uses go/parser and go/types for parsing and type checking,
// then walks the typed AST to emit instructions.
//
// Restrictions (enforced at compile time):
//   - Types: int64, float64, bool, string, []int64, []float64, []bool, []string
//   - Allowed: function decls, local vars, arithmetic, comparisons, booleans,
//     if/else, for-range over collections, return, calling builtins,
//     calling other functions in the same compilation unit
//   - Rejected: pointers, maps, interfaces, goroutines, channels, closures,
//     methods, make/new/append, import, goto, defer/panic/recover,
//     nested collections, arbitrary for-loops, recursion
package compile

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"go/types"

	"mazzy/mazarin/vm"
)

// Result is the output of a successful compilation.
type Result struct {
	Program *vm.Program
	Func    string // entry function name
}

// Compile parses a Go source string containing one or more functions
// and compiles them to VM bytecode. The last user-defined function
// is the entry point; preceding functions are helpers.
func Compile(src string) (*Result, error) {
	fset := token.NewFileSet()

	// Wrap in a package with builtin stubs so go/types can type-check calls
	// to our VM builtins (clamp, str_*, coll_*, etc.).
	wrapped := "package constraint\n\n" + builtinStubs + "\n" + src
	file, err := parser.ParseFile(fset, "constraint.go", wrapped, 0)
	if err != nil {
		return nil, fmt.Errorf("parse error: %w", err)
	}

	// Collect user function declarations (skip builtin stubs).
	var fnDecls []*ast.FuncDecl
	for _, decl := range file.Decls {
		if fd, ok := decl.(*ast.FuncDecl); ok {
			if _, isStub := builtinStubNames[fd.Name.Name]; isStub {
				continue
			}
			fnDecls = append(fnDecls, fd)
		}
	}
	if len(fnDecls) == 0 {
		return nil, fmt.Errorf("no function declaration found")
	}

	// Type-check.
	conf := types.Config{Importer: nil}
	info := &types.Info{
		Types: make(map[ast.Expr]types.TypeAndValue),
		Defs:  make(map[*ast.Ident]types.Object),
		Uses:  make(map[*ast.Ident]types.Object),
	}
	_, err = conf.Check("constraint", fset, []*ast.File{file}, info)
	if err != nil {
		return nil, fmt.Errorf("type error: %w", err)
	}

	// Build function table: name → index.
	funcTable := make(map[string]int, len(fnDecls))
	for i, fd := range fnDecls {
		funcTable[fd.Name.Name] = i
	}

	// First pass: count locals per function to assign non-overlapping slot ranges.
	localCounts := make([]uint16, len(fnDecls))
	for i, fd := range fnDecls {
		localCounts[i] = countFuncLocals(fd)
	}
	localBases := make([]uint16, len(fnDecls))
	var nextBase uint16
	for i, count := range localCounts {
		localBases[i] = nextBase
		nextBase += count
	}

	// Compile each function.
	c := &compiler{
		fset:      fset,
		info:      info,
		funcTable: funcTable,
		fnDecls:   fnDecls,
	}

	funcInfos := make([]vm.FuncInfo, len(fnDecls))
	for i, fd := range fnDecls {
		c.fnDecl = fd
		c.locals = make(map[string]uint16)
		c.nextLocal = localBases[i]
		c.localBase = localBases[i]
		c.numReturns = 0

		if err := c.checkRestrictions(); err != nil {
			return nil, err
		}

		startPC := uint16(len(c.code))
		if err := c.compileFn(); err != nil {
			return nil, err
		}

		funcInfos[i] = vm.FuncInfo{
			Name:      fd.Name.Name,
			PC:        startPC,
			NumArgs:   countDeclParams(fd),
			NumLocals: c.nextLocal - localBases[i],
			LocalBase: localBases[i],
		}
	}

	entryIdx := len(fnDecls) - 1
	entryDecl := fnDecls[entryIdx]

	// Build param types for the entry function.
	c.fnDecl = entryDecl
	argTypes := c.paramTypes()

	prog := &vm.Program{
		Code:     c.code,
		Strings:  c.strTable,
		NumArgs:  countDeclParams(entryDecl),
		ArgTypes: argTypes,
		Funcs:    funcInfos,
		Entry:    uint16(entryIdx),
	}

	// Verify the generated bytecode.
	if err := vm.Verify(prog); err != nil {
		return nil, fmt.Errorf("internal compiler error: generated invalid bytecode: %w", err)
	}

	return &Result{
		Program: prog,
		Func:    entryDecl.Name.Name,
	}, nil
}

type compiler struct {
	fset   *token.FileSet
	info   *types.Info
	fnDecl *ast.FuncDecl // current function being compiled

	// Multi-function state.
	funcTable map[string]int       // function name → index in fnDecls
	fnDecls   []*ast.FuncDecl      // all user function declarations

	// Code emission (shared across all functions).
	code     []vm.Inst
	strTable []string
	strIndex map[string]uint16 // dedup string constants

	// Per-function local state (reset between functions).
	locals    map[string]uint16 // variable name → local slot
	nextLocal uint16            // next available local slot
	localBase uint16            // base slot for current function

	// Track return count for RET instruction.
	numReturns int

	strings map[string]uint16 // string constant dedup
}

func (c *compiler) emit(inst vm.Inst) {
	c.code = append(c.code, inst)
}

func (c *compiler) errAt(pos token.Pos, format string, args ...any) error {
	position := c.fset.Position(pos)
	// Adjust line number for the "package constraint\n\n" wrapper.
	position.Line -= 2
	return fmt.Errorf("%s: %s", position, fmt.Sprintf(format, args...))
}

// allocLocal returns the slot for a variable, allocating one if new.
func (c *compiler) allocLocal(name string) uint16 {
	if slot, ok := c.locals[name]; ok {
		return slot
	}
	slot := c.nextLocal
	c.nextLocal++
	c.locals[name] = slot
	return slot
}

// lookupLocal returns the slot for an existing variable.
func (c *compiler) lookupLocal(name string) (uint16, bool) {
	slot, ok := c.locals[name]
	return slot, ok
}

// addString adds a string to the constant table and returns its index.
func (c *compiler) addString(s string) uint16 {
	if c.strIndex == nil {
		c.strIndex = make(map[string]uint16)
	}
	if idx, ok := c.strIndex[s]; ok {
		return idx
	}
	idx := uint16(len(c.strTable))
	c.strTable = append(c.strTable, s)
	c.strIndex[s] = idx
	return idx
}

// countDeclParams returns the actual number of parameters for a FuncDecl.
func countDeclParams(fd *ast.FuncDecl) uint16 {
	if fd.Type.Params == nil {
		return 0
	}
	var n uint16
	for _, field := range fd.Type.Params.List {
		if len(field.Names) == 0 {
			n++
		} else {
			n += uint16(len(field.Names))
		}
	}
	return n
}

// paramTypes returns the VM type tag for each parameter of the current function.
func (c *compiler) paramTypes() []uint8 {
	if c.fnDecl.Type.Params == nil {
		return nil
	}
	var types []uint8
	for _, field := range c.fnDecl.Type.Params.List {
		t, ok := c.resolveTypeExpr(field.Type)
		if !ok {
			t = vm.TypeI64 // fallback
		}
		if len(field.Names) == 0 {
			types = append(types, t)
		} else {
			for range field.Names {
				types = append(types, t)
			}
		}
	}
	return types
}

// countFuncLocals walks a function's AST to count the total number of
// unique local variable slots needed (parameters + body locals).
func countFuncLocals(fd *ast.FuncDecl) uint16 {
	names := make(map[string]bool)
	// Parameters.
	if fd.Type.Params != nil {
		for _, field := range fd.Type.Params.List {
			for _, name := range field.Names {
				names[name.Name] = true
			}
		}
	}
	// Walk body for assignments and range variables.
	countLocalsInStmts(fd.Body.List, names)
	return uint16(len(names))
}

func countLocalsInStmts(stmts []ast.Stmt, names map[string]bool) {
	for _, stmt := range stmts {
		switch s := stmt.(type) {
		case *ast.AssignStmt:
			for _, lhs := range s.Lhs {
				if id, ok := lhs.(*ast.Ident); ok {
					names[id.Name] = true
				}
			}
		case *ast.RangeStmt:
			if s.Key != nil {
				if id, ok := s.Key.(*ast.Ident); ok {
					names[id.Name] = true
				}
			}
			if s.Value != nil {
				if id, ok := s.Value.(*ast.Ident); ok {
					names[id.Name] = true
				}
			}
			countLocalsInStmts(s.Body.List, names)
		case *ast.IfStmt:
			countLocalsInStmts(s.Body.List, names)
			if s.Else != nil {
				switch e := s.Else.(type) {
				case *ast.BlockStmt:
					countLocalsInStmts(e.List, names)
				case *ast.IfStmt:
					countLocalsInStmts([]ast.Stmt{e}, names)
				}
			}
		case *ast.BlockStmt:
			countLocalsInStmts(s.List, names)
		case *ast.IncDecStmt:
			if id, ok := s.X.(*ast.Ident); ok {
				names[id.Name] = true
			}
		}
	}
}

// goTypeToVMType maps a Go type to a VM type tag.
func goTypeToVMType(t types.Type) (uint8, bool) {
	switch t := t.Underlying().(type) {
	case *types.Basic:
		switch t.Kind() {
		case types.Int64:
			return vm.TypeI64, true
		case types.Float64:
			return vm.TypeF64, true
		case types.Bool:
			return vm.TypeBool, true
		case types.String:
			return vm.TypeStr, true
		case types.UntypedInt:
			return vm.TypeI64, true
		case types.UntypedFloat:
			return vm.TypeF64, true
		case types.UntypedBool:
			return vm.TypeBool, true
		case types.UntypedString:
			return vm.TypeStr, true
		}
	case *types.Slice:
		if elem, ok := goTypeToVMType(t.Elem()); ok {
			switch elem {
			case vm.TypeI64:
				return vm.TypeCollI64, true
			case vm.TypeF64:
				return vm.TypeCollF64, true
			case vm.TypeBool:
				return vm.TypeCollBool, true
			case vm.TypeStr:
				return vm.TypeCollStr, true
			}
		}
	}
	return 0, false
}

// isNumericType returns true for I64 or F64.
func isNumericType(t uint8) bool {
	return t == vm.TypeI64 || t == vm.TypeF64
}

// builtinStubs provides Go source declarations for our VM builtins so
// go/types can type-check programs that call them. Types are approximate —
// the actual dispatch is by name, and the VM handles types at runtime.
const builtinStubs = `
func clamp(val, lo, hi int64) int64 { return 0 }
func minf(a, b float64) float64 { return 0 }
func maxf(a, b float64) float64 { return 0 }
func clampf(val, lo, hi float64) float64 { return 0 }
func sqrt(x float64) float64 { return 0 }
func floor(x float64) float64 { return 0 }
func ceil(x float64) float64 { return 0 }
func round(x float64) float64 { return 0 }
func str_len(s string) int64 { return 0 }
func str_concat(a, b string) string { return "" }
func str_contains(s, sub string) bool { return false }
func str_substr(s string, start, length int64) string { return "" }
func str_prefix(s, prefix string) bool { return false }
func str_suffix(s, suffix string) bool { return false }
func str_upper(s string) string { return "" }
func str_lower(s string) string { return "" }
func coll_len(c []int64) int64 { return 0 }
func coll_get(c []int64, i int64) int64 { return 0 }
func coll_take(c []int64, n int64) []int64 { return nil }
func coll_drop(c []int64, n int64) []int64 { return nil }
func coll_sort(c []int64) []int64 { return nil }
func coll_concat(a, b []int64) []int64 { return nil }
func coll_page(c []int64, page, size int64) []int64 { return nil }
func coll_empty() []int64 { return nil }
`

// builtinStubNames is the set of function names injected as stubs.
var builtinStubNames = map[string]struct{}{
	"clamp": {}, "minf": {}, "maxf": {}, "clampf": {},
	"sqrt": {}, "floor": {}, "ceil": {}, "round": {},
	"str_len": {}, "str_concat": {}, "str_contains": {}, "str_substr": {},
	"str_prefix": {}, "str_suffix": {}, "str_upper": {}, "str_lower": {},
	"coll_len": {}, "coll_get": {}, "coll_take": {}, "coll_drop": {},
	"coll_sort": {}, "coll_concat": {}, "coll_page": {}, "coll_empty": {},
}
