version: '3'

tasks:
  arm64:
    desc: Build attrtest (Eval/Vite attribute library test shepherd, ARM64)
    run: once
    deps: [':check-env', ':mazarin:userspace-overlay']
    sources:
      - 'maz/attrtest/**/*.go'
      - 'mazarin/**/*.go'
      - '{{.USERSPACE_OVERLAY_JSON}}'
      - '{{.USERSPACE_OVERLAY_DIR}}/**/*'
    generates:
      - '{{.ATTRTEST_ELF}}'
    cmds:
      - '{{.GO}} tool go-echo "Building attrtest..."'
      - 'CGO_ENABLED=0 GOARCH={{.TARGET_GOARCH}} GOOS={{.TARGET_GOOS}} {{.GO}} build -overlay={{.ROOT_DIR}}/{{.USERSPACE_OVERLAY_JSON}} {{.GCFLAGS}} -o {{.ATTRTEST_ELF}} ./maz/attrtest'
      - '{{.GO}} tool go-echo "Attrtest built at {{.ATTRTEST_ELF}}"'

  x86_64:
    desc: Build attrtest (x86_64)
    run: once
    deps: [':check-env', ':mazarin:userspace-overlay']
    sources:
      - 'maz/attrtest/**/*.go'
      - 'mazarin/**/*.go'
      - '{{.USERSPACE_OVERLAY_JSON}}'
      - '{{.USERSPACE_OVERLAY_DIR}}/**/*'
    generates:
      - '{{.ATTRTEST_AMD64_ELF}}'
    cmds:
      - '{{.GO}} tool go-echo "Building attrtest for x86_64..."'
      - 'CGO_ENABLED=0 GOARCH=amd64 GOOS=linux {{.GO}} build -overlay={{.ROOT_DIR}}/{{.USERSPACE_OVERLAY_JSON}} {{.GCFLAGS}} -o {{.ATTRTEST_AMD64_ELF}} ./maz/attrtest'
      - '{{.GO}} tool go-echo "Attrtest x86_64 built at {{.ATTRTEST_AMD64_ELF}}"'

