// DO NOT EDIT THIS FILE. It is generated by the build system.
//
//go:generate go run ../../tools/generate-linknames.go -asm ../../asm/aarch64 -file linknames.go
package asm

import "unsafe"

// {{ LINKNAME START}}
//{{ LINKNAME END}}

// Manual entries (not auto-generated):

//go:linkname RunOnGoroutine runOnGoroutine
//go:nosplit
func RunOnGoroutine(g unsafe.Pointer, fn func())
