version: '3'

tasks:
  arm64:
    desc: Build fti shepherd (ARM64)
    run: once
    deps: [':check-env', ':merged-shepherd-overlay']
    sources:
      - 'maz/**/*.go'
      - 'maz/**/*.s'
      - 'mazarin/**/*.go'
      - '{{.MERGED_SHEPHERD_OVERLAY_JSON}}'
      - '{{.USERSPACE_OVERLAY_DIR}}/**/*'
      - '{{.SHEPHERD_OVERLAY_DIR}}/**/*'
    generates:
      - '{{.FTI_ELF}}'
    cmds:
      - '{{.GO}} tool go-echo "Building fti for ARM64..."'
      - 'CGO_ENABLED=0 GOARCH={{.TARGET_GOARCH}} GOOS={{.TARGET_GOOS}} {{.GO}} build -tags mazhost -overlay={{.ROOT_DIR}}/{{.MERGED_SHEPHERD_OVERLAY_JSON}} {{.GCFLAGS}} -o {{.FTI_ELF}} ./maz/fti'
      - '{{.GO}} tool go-echo "fti ARM64 built at {{.FTI_ELF}}"'

  x86_64:
    desc: Build fti shepherd (x86_64)
    run: once
    deps: [':check-env', ':merged-shepherd-overlay-amd64']
    sources:
      - 'maz/**/*.go'
      - 'maz/**/*.s'
      - 'mazarin/**/*.go'
      - '{{.MERGED_SHEPHERD_OVERLAY_AMD64_JSON}}'
      - '{{.USERSPACE_OVERLAY_DIR}}/**/*'
      - '{{.SHEPHERD_OVERLAY_AMD64_DIR}}/**/*'
    generates:
      - '{{.FTI_AMD64_ELF}}'
    cmds:
      - '{{.GO}} tool go-echo "Building fti for x86_64..."'
      - 'CGO_ENABLED=0 GOARCH=amd64 GOOS=linux {{.GO}} build -tags mazhost -overlay={{.ROOT_DIR}}/{{.MERGED_SHEPHERD_OVERLAY_AMD64_JSON}} {{.GCFLAGS}} -o {{.FTI_AMD64_ELF}} ./maz/fti'
      - '{{.GO}} tool go-echo "fti x86_64 built at {{.FTI_AMD64_ELF}}"'

  riscv64:
    desc: Build fti shepherd (RISC-V 64-bit)
    run: once
    deps: [':check-env', ':merged-shepherd-overlay-riscv64']
    sources:
      - 'maz/**/*.go'
      - 'maz/**/*.s'
      - 'mazarin/**/*.go'
      - '{{.MERGED_SHEPHERD_OVERLAY_RISCV64_JSON}}'
      - '{{.USERSPACE_OVERLAY_DIR}}/**/*'
      - '{{.SHEPHERD_OVERLAY_RISCV64_DIR}}/**/*'
    generates:
      - '{{.FTI_RISCV64_ELF}}'
    cmds:
      - '{{.GO}} tool go-echo "Building fti for RISC-V 64-bit..."'
      - 'CGO_ENABLED=0 GOARCH=riscv64 GOOS=linux {{.GO}} build -tags mazhost -overlay={{.ROOT_DIR}}/{{.MERGED_SHEPHERD_OVERLAY_RISCV64_JSON}} {{.GCFLAGS}} -o {{.FTI_RISCV64_ELF}} ./maz/fti'
      - '{{.GO}} tool go-echo "fti RISC-V 64-bit built at {{.FTI_RISCV64_ELF}}"'
