// extract-kmazarin-symbols.go
// Extracts symbol addresses and memory ranges from kmazarin.elf
// and generates a GNU assembly file with constants for use by mazboot.
//
// Usage: extract-kmazarin-symbols <kmazarin.elf> <output.s>
//
// NOTE: Uses nm and objdump instead of debug/elf package because Go's
// linker creates "negative" file offsets when using -T flag, which causes
// debug/elf to reject the file. See CLAUDE.md for details.

package main

import (
	"bufio"
	"fmt"
	"os"
	"os/exec"
	"strconv"
	"strings"
)

// Section represents a section from objdump output
type Section struct {
	Name  string
	Size  uint64
	VMA   uint64
	LMA   uint64
	Off   uint64
	Align uint64
}

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintf(os.Stderr, "Usage: %s <kmazarin.elf> <output.s>\n", os.Args[0])
		os.Exit(1)
	}

	inputPath := os.Args[1]
	outputPath := os.Args[2]

	// Extract symbols using nm
	symbolAddrs, err := extractSymbols(inputPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error extracting symbols: %v\n", err)
		os.Exit(1)
	}

	// Extract section information using objdump
	sections, err := extractSections(inputPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error extracting sections: %v\n", err)
		os.Exit(1)
	}

	// Find specific symbols we need
	requiredSymbols := []string{
		"runtime.asyncPreempt.abi0",
		"runtime.asyncPreempt2",
	}

	for _, name := range requiredSymbols {
		if addr, ok := symbolAddrs[name]; !ok {
			fmt.Fprintf(os.Stderr, "Warning: Symbol %s not found\n", name)
		} else {
			fmt.Fprintf(os.Stderr, "Found %s at 0x%016X\n", name, addr)
		}
	}

	// Find sections
	textSection, ok := sections[".text"]
	if !ok {
		fmt.Fprintf(os.Stderr, "Error: .text section not found\n")
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "Found .text at 0x%08X, size 0x%X\n", textSection.VMA, textSection.Size)

	// Generate the assembly file
	out, err := os.Create(outputPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error creating output file: %v\n", err)
		os.Exit(1)
	}
	defer out.Close()

	fmt.Fprintf(out, "// AUTO-GENERATED by extract-kmazarin-symbols\n")
	fmt.Fprintf(out, "// DO NOT EDIT - This file is regenerated whenever kmazarin.elf is rebuilt\n")
	fmt.Fprintf(out, "//\n")
	fmt.Fprintf(out, "// Source: %s\n", inputPath)
	fmt.Fprintf(out, "//\n\n")

	// Write symbol addresses
	fmt.Fprintf(out, "// ============================================================================\n")
	fmt.Fprintf(out, "// KMAZARIN SYMBOL ADDRESSES\n")
	fmt.Fprintf(out, "// ============================================================================\n\n")

	if addr, ok := symbolAddrs["runtime.asyncPreempt.abi0"]; ok {
		fmt.Fprintf(out, "// runtime.asyncPreempt.abi0 - Async preemption entry point\n")
		fmt.Fprintf(out, ".equ KMAZARIN_ASYNCPREEMPT, 0x%X\n\n", addr)
	}

	if addr, ok := symbolAddrs["runtime.asyncPreempt2"]; ok {
		fmt.Fprintf(out, "// runtime.asyncPreempt2 - Async preemption handler\n")
		fmt.Fprintf(out, ".equ KMAZARIN_ASYNCPREEMPT2, 0x%X\n\n", addr)
	}

	// Write memory ranges
	fmt.Fprintf(out, "// ============================================================================\n")
	fmt.Fprintf(out, "// KMAZARIN MEMORY RANGES\n")
	fmt.Fprintf(out, "// ============================================================================\n\n")

	fmt.Fprintf(out, "// .text section range (executable code)\n")
	fmt.Fprintf(out, ".equ KMAZARIN_TEXT_START, 0x%X\n", textSection.VMA)
	fmt.Fprintf(out, ".equ KMAZARIN_TEXT_END,   0x%X\n\n", textSection.VMA+textSection.Size)

	if rodataSection, ok := sections[".rodata"]; ok {
		fmt.Fprintf(out, "// .rodata section range (read-only data)\n")
		fmt.Fprintf(out, ".equ KMAZARIN_RODATA_START, 0x%X\n", rodataSection.VMA)
		fmt.Fprintf(out, ".equ KMAZARIN_RODATA_END,   0x%X\n\n", rodataSection.VMA+rodataSection.Size)
	}

	if dataSection, ok := sections[".data"]; ok {
		fmt.Fprintf(out, "// .data section range (read-write data)\n")
		fmt.Fprintf(out, ".equ KMAZARIN_DATA_START, 0x%X\n", dataSection.VMA)
		fmt.Fprintf(out, ".equ KMAZARIN_DATA_END,   0x%X\n\n", dataSection.VMA+dataSection.Size)
	}

	// Write helper macros for loading addresses
	fmt.Fprintf(out, "// ============================================================================\n")
	fmt.Fprintf(out, "// HELPER MACROS\n")
	fmt.Fprintf(out, "// ============================================================================\n\n")

	if addr, ok := symbolAddrs["runtime.asyncPreempt.abi0"]; ok {
		fmt.Fprintf(out, "// LOAD_KMAZARIN_ASYNCPREEMPT reg\n")
		fmt.Fprintf(out, "// Loads the address of runtime.asyncPreempt.abi0 into the specified register\n")
		fmt.Fprintf(out, ".macro LOAD_KMAZARIN_ASYNCPREEMPT reg\n")
		fmt.Fprintf(out, "    movz \\reg, #0x%X, lsl #16\n", (addr>>16)&0xFFFF)
		fmt.Fprintf(out, "    movk \\reg, #0x%X\n", addr&0xFFFF)
		fmt.Fprintf(out, ".endm\n\n")
	}

	fmt.Fprintf(os.Stderr, "Successfully generated %s\n", outputPath)
}

// extractSymbols runs nm and parses the output to get symbol addresses
func extractSymbols(elfPath string) (map[string]uint64, error) {
	// Use target-nm from ~/mazzy/bin (cross-compiler toolchain)
	// Fall back to system 'nm' if not found
	nmPath := os.ExpandEnv("$HOME/mazzy/bin/target-nm")
	if _, err := os.Stat(nmPath); err != nil {
		nmPath = "nm" // Fall back to system nm
	}

	// Run nm to get symbols
	cmd := exec.Command(nmPath, elfPath)
	output, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("failed to run nm: %w", err)
	}

	symbolAddrs := make(map[string]uint64)
	scanner := bufio.NewScanner(strings.NewReader(string(output)))

	// Parse nm output: each line is "address type name"
	// Example: 0000000041871b60 T runtime.asyncPreempt.abi0
	for scanner.Scan() {
		line := scanner.Text()
		fields := strings.Fields(line)
		if len(fields) < 3 {
			continue
		}

		addrStr := fields[0]
		name := fields[2]

		addr, err := strconv.ParseUint(addrStr, 16, 64)
		if err != nil {
			continue // Skip invalid addresses
		}

		symbolAddrs[name] = addr
	}

	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("error reading nm output: %w", err)
	}

	return symbolAddrs, nil
}

// extractSections runs objdump -h and parses section information
func extractSections(elfPath string) (map[string]Section, error) {
	// Use target-objdump from ~/mazzy/bin (cross-compiler toolchain)
	// Fall back to system 'objdump' if not found
	objdumpPath := os.ExpandEnv("$HOME/mazzy/bin/target-objdump")
	if _, err := os.Stat(objdumpPath); err != nil {
		objdumpPath = "objdump" // Fall back to system objdump
	}

	// Run objdump -h to get section headers
	cmd := exec.Command(objdumpPath, "-h", elfPath)
	output, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("failed to run objdump: %w", err)
	}

	sections := make(map[string]Section)
	scanner := bufio.NewScanner(strings.NewReader(string(output)))

	// Parse objdump -h output
	// Example line:
	//   0 .text         00094dd4  0000000041800000  0000000041800000  00001000  2**4
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || !strings.Contains(line, ".") {
			continue
		}

		fields := strings.Fields(line)
		if len(fields) < 7 {
			continue
		}

		// Check if this is a section line (first field is a number)
		if _, err := strconv.Atoi(fields[0]); err != nil {
			continue
		}

		name := fields[1]
		sizeStr := fields[2]
		vmaStr := fields[3]
		lmaStr := fields[4]
		offStr := fields[5]

		size, err := strconv.ParseUint(sizeStr, 16, 64)
		if err != nil {
			continue
		}

		vma, err := strconv.ParseUint(vmaStr, 16, 64)
		if err != nil {
			continue
		}

		lma, err := strconv.ParseUint(lmaStr, 16, 64)
		if err != nil {
			continue
		}

		off, err := strconv.ParseUint(offStr, 16, 64)
		if err != nil {
			continue
		}

		sections[name] = Section{
			Name:  name,
			Size:  size,
			VMA:   vma,
			LMA:   lma,
			Off:   off,
			Align: 0, // We don't parse alignment for now
		}
	}

	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("error reading objdump output: %w", err)
	}

	return sections, nil
}
