#!/usr/bin/env python3
"""
Helper script to insert content between markers in a file.

Usage:
    python3 insert-between-markers.py <target_file> <start_marker> <end_marker> <content_file>

Replaces the content between start_marker and end_marker in target_file
with the content from content_file.
"""

import sys
import os


def main():
    if len(sys.argv) != 5:
        print("Usage: insert-between-markers.py <target_file> <start_marker> <end_marker> <content_file>", file=sys.stderr)
        sys.exit(1)

    target_file = sys.argv[1]
    start_marker = sys.argv[2]
    end_marker = sys.argv[3]
    content_file = sys.argv[4]

    # Read target file (create if it doesn't exist)
    try:
        with open(target_file, 'r') as f:
            target_content = f.read()
    except FileNotFoundError:
        # File doesn't exist, create it with markers
        # Try to determine package name from directory structure
        if 'linknames.go' in target_file:
            target_content = """// DO NOT EDIT THIS FILE. It is generated by the build system.
package main

import "unsafe"

""" + start_marker + """

""" + end_marker + """
"""
        elif 'main.go' in target_file:
            target_content = """// DO NOT EDIT THIS FILE. It is generated by the build system.
package main

// Dummy main() function required by Go's c-archive build mode
// This is never called - boot.s calls KernelMain directly
// We call KernelMain here to ensure it's compiled and not optimized away
func main() {
""" + start_marker + """

""" + end_marker + """
	// This should never execute in bare metal
	for {
	}

}
"""
        else:
            # Generic template
            target_content = start_marker + """

""" + end_marker + """
"""
    except IOError as e:
        print(f"Error reading target file: {e}", file=sys.stderr)
        sys.exit(1)

    # Read content to insert
    try:
        with open(content_file, 'r') as f:
            new_content = f.read()
    except FileNotFoundError:
        print(f"Error: Content file not found: {content_file}", file=sys.stderr)
        sys.exit(1)
    except IOError as e:
        print(f"Error reading content file: {e}", file=sys.stderr)
        sys.exit(1)

    # Find markers
    start_idx = target_content.find(start_marker)
    end_idx = target_content.find(end_marker)

    if start_idx == -1:
        print(f"Error: Start marker not found: {start_marker}", file=sys.stderr)
        sys.exit(1)

    if end_idx == -1:
        print(f"Error: End marker not found: {end_marker}", file=sys.stderr)
        sys.exit(1)

    if end_idx <= start_idx:
        print(f"Error: End marker appears before start marker", file=sys.stderr)
        sys.exit(1)

    # Find the end of the start marker line (include newline)
    start_line_end = start_idx + len(start_marker)
    while start_line_end < len(target_content) and target_content[start_line_end] != '\n':
        start_line_end += 1
    if start_line_end < len(target_content):
        start_line_end += 1  # Include the newline

    # Find the start of the end marker line
    end_line_start = end_idx
    while end_line_start > 0 and target_content[end_line_start - 1] != '\n':
        end_line_start -= 1

    # Reconstruct the file
    new_file_content = (
        target_content[:start_line_end] +
        new_content +
        target_content[end_line_start:]
    )

    # Write back to target file
    try:
        with open(target_file, 'w') as f:
            f.write(new_file_content)
    except IOError as e:
        print(f"Error writing target file: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()



