version: '3'

tasks:
  arm64:
    desc: Build fs shepherd (standalone filesystem server, ARM64)
    run: once
    deps: [':check-env', ':merged-shepherd-overlay']
    sources:
      - 'flock/**/*.go'
      - 'flock/**/*.s'
      - 'mazarin/**/*.go'
      - 'shared/**/*.go'
      - '{{.MERGED_SHEPHERD_OVERLAY_JSON}}'
      - '{{.USERSPACE_OVERLAY_DIR}}/**/*'
      - '{{.SHEPHERD_OVERLAY_DIR}}/**/*'
    generates:
      - '{{.FS_ELF}}'
    cmds:
      - '{{.GO}} tool go-echo "Building fs shepherd for ARM64..."'
      - 'CGO_ENABLED=0 GOARCH={{.TARGET_GOARCH}} GOOS={{.TARGET_GOOS}} {{.GO}} build -overlay={{.ROOT_DIR}}/{{.MERGED_SHEPHERD_OVERLAY_JSON}} {{.GCFLAGS}} -o {{.FS_ELF}} ./flock/cmd/fs'
      - '{{.GO}} tool go-echo "FS shepherd ARM64 built at {{.FS_ELF}}"'

  x86_64:
    desc: Build fs shepherd (standalone filesystem server, x86_64)
    run: once
    deps: [':check-env', ':merged-shepherd-overlay-amd64']
    sources:
      - 'flock/**/*.go'
      - 'flock/**/*.s'
      - 'mazarin/**/*.go'
      - 'shared/**/*.go'
      - '{{.MERGED_SHEPHERD_OVERLAY_AMD64_JSON}}'
      - '{{.USERSPACE_OVERLAY_DIR}}/**/*'
      - '{{.SHEPHERD_OVERLAY_AMD64_DIR}}/**/*'
    generates:
      - '{{.FS_AMD64_ELF}}'
    cmds:
      - '{{.GO}} tool go-echo "Building fs shepherd for x86_64..."'
      - 'CGO_ENABLED=0 GOARCH=amd64 GOOS=linux {{.GO}} build -overlay={{.ROOT_DIR}}/{{.MERGED_SHEPHERD_OVERLAY_AMD64_JSON}} {{.GCFLAGS}} -o {{.FS_AMD64_ELF}} ./flock/cmd/fs'
      - '{{.GO}} tool go-echo "FS shepherd x86_64 built at {{.FS_AMD64_ELF}}"'

  riscv64:
    desc: Build fs shepherd (standalone filesystem server, RISC-V 64-bit)
    run: once
    deps: [':check-env', ':merged-shepherd-overlay-riscv64']
    sources:
      - 'flock/**/*.go'
      - 'flock/**/*.s'
      - 'mazarin/**/*.go'
      - 'shared/**/*.go'
      - '{{.MERGED_SHEPHERD_OVERLAY_RISCV64_JSON}}'
      - '{{.USERSPACE_OVERLAY_DIR}}/**/*'
      - '{{.SHEPHERD_OVERLAY_RISCV64_DIR}}/**/*'
    generates:
      - '{{.FS_RISCV64_ELF}}'
    cmds:
      - '{{.GO}} tool go-echo "Building fs shepherd for RISC-V 64-bit..."'
      - 'CGO_ENABLED=0 GOARCH=riscv64 GOOS=linux {{.GO}} build -overlay={{.ROOT_DIR}}/{{.MERGED_SHEPHERD_OVERLAY_RISCV64_JSON}} {{.GCFLAGS}} -o {{.FS_RISCV64_ELF}} ./flock/cmd/fs'
      - '{{.GO}} tool go-echo "FS shepherd RISC-V 64-bit built at {{.FS_RISCV64_ELF}}"'
