//go:build test_stubs

// Code generated by tools/gen-test-stubs.go. DO NOT EDIT.

package kirq

// Exported functions (forward declarations replaced with stubs)
func Exit() {}
func TimerIRQHandlerAsm() {}

// Unexported functions (forward declarations replaced with stubs)
func breadcrumbString(s string) {}
func breadcrumbHex(val uint64) {}
func getPreemptOffsets() preemptOffsetsType { return preemptOffsetsType{} }
func getAsyncPreemptAddr() (uintptr) { return 0 }
func getReadyForAsyncPreemptAddr() (uintptr) { return 0 }
func processDeadlines() {}
func asm_rearmTimer(ticks uint64) {}
func asm_readCntfrqEl0() (uint32) { return 0 }
func asm_readCntvctEl0() (uint64) { return 0 }
func asmYieldSVC() {}
