//go:build test_stubs

// Code generated by tools/gen-test-stubs.go. DO NOT EDIT.

package kirq

// Exported functions (forward declarations replaced with stubs)
func Exit() {}
func TimerIRQHandlerAsm() {}

// Unexported functions (forward declarations replaced with stubs)
func getPreemptOffsets() preemptOffsetsType { return preemptOffsetsType{} }
func getAsyncPreemptAddr() (uintptr) { return 0 }
func getReadyForAsyncPreemptAddr() (uintptr) { return 0 }
func processDeadlines() {}
// Timer assembly stubs moved to ktimer/platform_stubs.go
func asmYieldSVC() {}
