// Code generated by generate-main-calls.go. DO NOT EDIT.
// Run 'make generate-main' to regenerate.

package main

// Dummy main() function required by Go's c-archive build mode
// This is never called - boot.s calls KernelMain directly
// We call functions here to ensure they're compiled and not optimized away
func main() {
	// Call kernel initialization functions to ensure they're compiled
	// This will never execute in bare metal, but ensures the functions exist
	KernelMain(0, 0, 0)

	// Reference other functions called from assembly
	// This will never execute in bare metal, but ensures the functions exist
	// Using _ to discard return values; arguments are dummy values
	_ = DoContextSwitch(0, 0)
	// IRQDispatchGo is called from exc_irq_arm64.s (stub in abi_stubs_arm64.s calls Internal)
	_, _, _, _ = IRQDispatchGo(0, 0, 0, 0, 0)
	// SyncExceptionDispatch is called from exc_syscall_arm64.s (manual stub in abi_stubs_arm64.s)
	_, _, _ = SyncExceptionDispatch(nil, 0, 0, 0, 0, 0, 0, 0)
	timerPreempt()
	writeBarrierDummyBufferKeepAlive()

	// This should never execute in bare metal
	for {
	}
}
