// Code generated by gen.go; DO NOT EDIT.

package main

// UnpackPageFlags unpacks a uint32 into a PageFlags struct.
func UnpackPageFlags(packed uint32) PageFlags {
	var flags PageFlags
	flags.Allocated = (packed>>0)&0x1 != 0
	flags.KernelPage = (packed>>1)&0x1 != 0
	flags.Reserved = uint32((packed>>2)&0x3fffffff)
	return flags
}

// PackPageFlags packs a PageFlags struct into a uint32.
// This function explicitly ensures the result is 32 bits, even on 64-bit systems.
func PackPageFlags(flags PageFlags) uint32 {
	var packed uint32
	if flags.Allocated {
		packed |= (1 << 0)
	}
	if flags.KernelPage {
		packed |= (1 << 1)
	}
	packed |= (uint32(flags.Reserved) & 0x3fffffff) << 2
	return packed
}
