//go:build ignore
// +build ignore

// Code generator for linknames.go
// Scans assembly files to generate //go:linkname declarations for assembly symbols
// Generates a complete Go file (no markers needed).
//
// Supports both:
//   - GCC assembly (.global directives in asm/aarch64/)
//   - Go/Plan9 assembly (TEXT directives in asm/goasm/)
//
// Usage: go run generate-linknames.go [-asm <dir>] [-goasm <dir>] [-o <path>]
//   -asm: GCC assembly source directory (default: asm/aarch64)
//   -goasm: Go/Plan9 assembly source directory (default: asm/goasm)
//   -o: Output Go file (default: stdout)

package main

import (
	"flag"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

func main() {
	// Parse command line flags
	var outputFile string
	var asmDir string
	var goasmDir string
	flag.StringVar(&asmDir, "asm", "asm/aarch64", "GCC assembly source directory")
	flag.StringVar(&goasmDir, "goasm", "asm/goasm", "Go/Plan9 assembly source directory")
	flag.StringVar(&outputFile, "o", "", "Output file (default: stdout)")
	flag.Parse()

	// Find all .global symbols from GCC assembly
	globalSymbols := findGlobalSymbols(asmDir)

	// Find all TEXT symbols from Go/Plan9 assembly and merge
	goasmSymbols := findGoAsmSymbols(goasmDir)
	globalSymbols = append(globalSymbols, goasmSymbols...)

	// Deduplicate symbols (some may be defined in both GCC and Go assembly during migration)
	globalSymbols = deduplicateSymbols(globalSymbols)

	// Generate the complete file
	var generated strings.Builder
	generateCompleteFile(globalSymbols, asmDir, goasmDir, &generated)

	// Format with gofmt
	formatted, err := formatWithGofmt(generated.String())
	if err != nil {
		fmt.Fprintf(os.Stderr, "Warning: gofmt failed, using unformatted output: %v\n", err)
		formatted = generated.String()
	}

	// Write output
	if outputFile == "" {
		// Write to stdout
		fmt.Print(formatted)
	} else {
		if err := ioutil.WriteFile(outputFile, []byte(formatted), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "Error writing to %s: %v\n", outputFile, err)
			os.Exit(1)
		}
		fmt.Fprintf(os.Stderr, "Generated %s\n", outputFile)
	}
}

// formatWithGofmt formats Go code using gofmt
func formatWithGofmt(code string) (string, error) {
	cmd := exec.Command("gofmt", "-s")
	cmd.Stdin = strings.NewReader(code)
	output, err := cmd.Output()
	if err != nil {
		return "", err
	}
	return string(output), nil
}

// generateCompleteFile generates the complete linknames.go file
func generateCompleteFile(globalSymbols []string, asmDir string, goasmDir string, w io.Writer) {
	// Write file header
	fmt.Fprintln(w, "// Code generated by generate-linknames.go. DO NOT EDIT.")
	fmt.Fprintln(w, "// Run 'make generate-linknames' to regenerate.")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "package asm")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "import \"unsafe\"")
	fmt.Fprintln(w, "")

	// Symbols to exclude (not meant for Go linking)
	excluded := map[string]bool{
		"_start":                         true,
		"kernel_main":                    true,
		"exception_vectors":              true,
		"exception_vectors_start_addr":   true,
		"exception_vectors_end":          true,
		"imageDataStart":                 true,
		"imageDataEnd":                   true,
		"write_barrier_dummy_buffer":     true,
		"_binary_boot_mazarin_bin_start": true,
		"_binary_boot_mazarin_bin_end":   true,
		"_binary_boot_mazarin_bin_size":  true,
	}

	// Filter and collect valid symbols with their signatures
	type symbolInfo struct {
		name       string
		goName     string
		signature  string
		returnType string
	}

	var symbols []symbolInfo

	// Parse GCC assembly files to get function signatures
	signatures := parseFunctionSignatures(asmDir)

	// Parse Go assembly files and merge their signatures
	goAsmSigs := parseGoAsmSignatures(goasmDir)
	for name, sig := range goAsmSigs {
		signatures[name] = sig
	}

	for _, sym := range globalSymbols {
		// Skip excluded symbols
		if excluded[sym] {
			continue
		}

		// Skip runtime.* symbols (Go runtime handles these)
		if strings.HasPrefix(sym, "runtime.") {
			continue
		}

		// Skip _binary_* linker symbols
		if strings.HasPrefix(sym, "_binary_") {
			continue
		}

		// Convert assembly symbol name to Go function name
		goName := convertToGoName(sym)

		// Get signature from parsed data
		sig, hasSig := signatures[sym]
		var params, retType string
		if hasSig {
			params = sig.params
			retType = sig.returnType
		} else {
			params = ""
			retType = ""
		}

		// Special case: MemmoveBytes is an alias for memmove
		if sym == "MemmoveBytes" && retType == "" {
			if memmoveSig, ok := signatures["memmove"]; ok {
				if params == "" {
					params = memmoveSig.params
				}
				if retType == "" {
					retType = memmoveSig.returnType
				}
			}
		}

		// Special cases for return types that aren't detected automatically
		if retType == "" {
			returnTypeOverrides := map[string]string{
				"get_caller_stack_pointer":  "uintptr",
				"mmio_read":                 "uint32",
				"mmio_read16":               "uint16",
				"get_g0_addr":               "uintptr",
				"get_m0_addr":               "uintptr",
				"get_mcache0_addr":          "uintptr",
				"get_emptymspan_addr":       "uintptr",
				"call_runtime_args":         "int",
				"get_current_g":             "uintptr",
				"get_stack_pointer":         "uintptr",
				"getGRegister":              "uintptr",
				"get_phys_page_size_addr":   "uintptr",
				"read_esr_el1":              "uint64",
				"read_elr_el1":              "uint64",
				"read_far_el1":              "uint64",
				"get_asyncPreemptBM_addr":   "uintptr",
			}
			if override, ok := returnTypeOverrides[sym]; ok {
				retType = override
			}
		}

		// Special cases for parameters that aren't detected automatically
		if params == "" {
			paramOverrides := map[string]string{
				"switchToGoroutine":      "g unsafe.Pointer",
				"mmio_write":             "reg uintptr, data uint32",
				"mmio_read":              "reg uintptr",
				"mmio_write16":           "reg uintptr, data uint16",
				"mmio_read16":            "reg uintptr",
				"mmio_write64":           "reg uintptr, data uint64",
				"store_pointer_nobarrier": "dest uintptr, value uintptr",
				"set_stack_pointer":      "sp uintptr",
				"set_g_pointer":          "g uintptr",
				"set_current_g":          "gptr uintptr",
				"write_elr_el1":          "value uint64",
			}
			if override, ok := paramOverrides[sym]; ok {
				params = override
			}
		}

		symbols = append(symbols, symbolInfo{
			name:       sym,
			goName:     goName,
			signature:  params,
			returnType: retType,
		})
	}

	// Sort by Go function name for consistent output
	sort.Slice(symbols, func(i, j int) bool {
		return symbols[i].goName < symbols[j].goName
	})

	// Deduplicate by Go function name (keeps first occurrence which is sorted alphabetically by asm name)
	// This handles cases where e.g. both "kmazarin_binary_start" and "KmazarinBinaryStart" exist
	seenGoNames := make(map[string]bool)
	var dedupedSymbols []symbolInfo
	for _, sym := range symbols {
		if !seenGoNames[sym.goName] {
			seenGoNames[sym.goName] = true
			dedupedSymbols = append(dedupedSymbols, sym)
		}
	}
	symbols = dedupedSymbols

	// Generate output
	for _, sym := range symbols {
		// Generate //go:linkname directive
		fmt.Fprintf(w, "//go:linkname %s %s\n", sym.goName, sym.name)
		fmt.Fprintf(w, "//go:nosplit\n")

		// Generate function signature
		if sym.returnType != "" {
			fmt.Fprintf(w, "func %s(%s) %s\n\n", sym.goName, sym.signature, sym.returnType)
		} else if sym.signature != "" {
			fmt.Fprintf(w, "func %s(%s)\n\n", sym.goName, sym.signature)
		} else {
			fmt.Fprintf(w, "func %s()\n\n", sym.goName)
		}
	}

	// Add manual entries at the end (functions with special signatures not auto-detected)
	fmt.Fprintln(w, "// Manual entries (special signatures not auto-detected):")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "//go:linkname RunOnGoroutine runOnGoroutine")
	fmt.Fprintln(w, "//go:nosplit")
	fmt.Fprintln(w, "func RunOnGoroutine(g unsafe.Pointer, fn func())")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "//go:linkname CallOnG0Stack callOnG0Stack")
	fmt.Fprintln(w, "//go:nosplit")
	fmt.Fprintln(w, "func CallOnG0Stack(fn func())")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "// Cache maintenance with explicit parameter types:")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "//go:linkname DcCvauManual DcCvau")
	fmt.Fprintln(w, "//go:nosplit")
	fmt.Fprintln(w, "func DcCvauManual(addr uintptr)")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "//go:linkname IcIvauManual IcIvau")
	fmt.Fprintln(w, "//go:nosplit")
	fmt.Fprintln(w, "func IcIvauManual(addr uintptr)")
}

// convertToGoName converts assembly symbol name to Go function name
func convertToGoName(asmName string) string {
	// Special cases - functions that need specific Go names
	specialCases := map[string]string{
		"store_pointer_nobarrier":      "StorePointerNoBarrier",
		"get_caller_stack_pointer":     "GetCallerStackPointer",
		"verify_stack_pointer_reading": "VerifyStackPointerReading",
		"switchToGoroutine":            "SwitchToGoroutine",
		"systemstack":                  "systemstack",
		"dsb":                          "Dsb",
		"isb":                          "Isb",
	}

	if goName, ok := specialCases[asmName]; ok {
		return goName
	}

	// If already CamelCase (starts with uppercase), keep as-is
	if len(asmName) > 0 && asmName[0] >= 'A' && asmName[0] <= 'Z' {
		return asmName
	}

	// Convert snake_case to CamelCase
	parts := strings.Split(asmName, "_")
	if len(parts) == 1 && len(asmName) <= 6 {
		// Short single-word names: capitalize first letter for export
		if len(asmName) > 0 {
			return strings.ToUpper(string(asmName[0])) + asmName[1:]
		}
	}

	// For compound names, convert snake_case to CamelCase
	if len(parts) > 1 {
		var result strings.Builder
		for _, part := range parts {
			if len(part) > 0 {
				result.WriteString(strings.ToUpper(string(part[0])))
				if len(part) > 1 {
					result.WriteString(part[1:])
				}
			}
		}
		return result.String()
	}

	return asmName
}

// functionSignature holds parsed function signature info
type functionSignature struct {
	params     string
	returnType string
}

// parseFunctionSignatures parses GCC assembly files to extract function signatures from comments
func parseFunctionSignatures(asmDir string) map[string]functionSignature {
	signatures := make(map[string]functionSignature)

	sigRe := regexp.MustCompile(`^//\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*\(([^)]*)\)`)
	returnRe := regexp.MustCompile(`(?i)^//.*\breturns?\b[: ]*\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*(?:\(|in\s+[wx]\d+|$)`)
	paramsRe := regexp.MustCompile(`Parameters:\s*(.+)`)

	filepath.Walk(asmDir, func(path string, info os.FileInfo, err error) error {
		if err != nil || !strings.HasSuffix(path, ".s") {
			return nil
		}

		content, err := ioutil.ReadFile(path)
		if err != nil {
			return nil
		}

		lines := strings.Split(string(content), "\n")
		for i, line := range lines {
			var returnType string
			var funcNameFromReturn string

			if strings.HasPrefix(strings.TrimSpace(line), "//") {
				returnMatches := returnRe.FindStringSubmatch(line)
				if len(returnMatches) >= 2 {
					returnType = strings.TrimSpace(returnMatches[1])
					for j := i - 1; j >= 0 && j >= i-10; j-- {
						prevLine := lines[j]
						trimmed := strings.TrimSpace(prevLine)
						if strings.HasPrefix(trimmed, "//") {
							funcMatch := regexp.MustCompile(`^//\s*([a-zA-Z_][a-zA-Z0-9_]+)\s*\(\)`).FindStringSubmatch(trimmed)
							if len(funcMatch) >= 2 {
								funcNameFromReturn = funcMatch[1]
								break
							}
							funcMatch = regexp.MustCompile(`^//\s*([a-zA-Z_][a-zA-Z0-9_]+)\s*[-:]`).FindStringSubmatch(trimmed)
							if len(funcMatch) >= 2 {
								funcNameFromReturn = funcMatch[1]
								break
							}
						}
					}
				}
			}

			matches := sigRe.FindStringSubmatch(line)
			if len(matches) >= 3 {
				funcName := matches[1]
				paramsStr := matches[2]

				if returnType == "" && i+1 < len(lines) {
					returnMatches := returnRe.FindStringSubmatch(lines[i+1])
					if len(returnMatches) >= 2 {
						returnType = strings.TrimSpace(returnMatches[1])
					}
				}
				if returnType == "" {
					returnMatches := returnRe.FindStringSubmatch(line)
					if len(returnMatches) >= 2 {
						returnType = strings.TrimSpace(returnMatches[1])
					}
				}

				goParams := convertCParamsToGo(paramsStr)
				goReturnType := convertCTypeToGo(returnType)

				signatures[funcName] = functionSignature{
					params:     goParams,
					returnType: goReturnType,
				}
			}

			if returnType != "" && funcNameFromReturn != "" {
				if _, exists := signatures[funcNameFromReturn]; !exists {
					signatures[funcNameFromReturn] = functionSignature{
						params:     "",
						returnType: convertCTypeToGo(returnType),
					}
				} else {
					existing := signatures[funcNameFromReturn]
					if existing.returnType == "" {
						existing.returnType = convertCTypeToGo(returnType)
						signatures[funcNameFromReturn] = existing
					}
				}
			}

			paramMatches := paramsRe.FindStringSubmatch(line)
			if len(paramMatches) >= 2 {
				var funcName string
				if i > 0 {
					prevLine := lines[i-1]
					funcNameMatch := regexp.MustCompile(`^//\s*([a-zA-Z_][a-zA-Z0-9_]+)`).FindStringSubmatch(prevLine)
					if len(funcNameMatch) >= 2 {
						funcName = funcNameMatch[1]
					}
				}
				if funcName == "" {
					funcNameMatch := regexp.MustCompile(`^//\s*([a-zA-Z_][a-zA-Z0-9_]+)`).FindStringSubmatch(line)
					if len(funcNameMatch) >= 2 {
						funcName = funcNameMatch[1]
					}
				}

				if funcName != "" {
					paramsStr := paramMatches[1]
					var paramType string
					parenMatch := regexp.MustCompile(`\(([^)]+)\)`).FindStringSubmatch(paramsStr)
					if len(parenMatch) >= 2 {
						paramType = strings.TrimSpace(parenMatch[1])
					} else {
						equalMatch := regexp.MustCompile(`=\s*([a-zA-Z_][a-zA-Z0-9_]*)\s`).FindStringSubmatch(paramsStr)
						if len(equalMatch) >= 2 {
							paramType = strings.TrimSpace(equalMatch[1])
						}
					}
					if paramType != "" {
						goType := convertCTypeToGo(paramType)
						if goType == "" {
							goType = "byte"
						}
						signatures[funcName] = functionSignature{
							params:     fmt.Sprintf("c %s", goType),
							returnType: "",
						}
					}
				}
			}
		}

		return nil
	})

	return signatures
}

// convertCParamsToGo converts C-style parameter list to Go-style
func convertCParamsToGo(cParams string) string {
	if strings.TrimSpace(cParams) == "" {
		return ""
	}

	params := strings.Split(cParams, ",")
	var goParams []string

	for _, p := range params {
		p = strings.TrimSpace(p)
		if p == "" {
			continue
		}

		var isPtr bool
		var cType, paramName string

		if strings.HasPrefix(p, "*") {
			isPtr = true
			rest := strings.TrimSpace(strings.TrimPrefix(p, "*"))
			parts := strings.Fields(rest)
			if len(parts) >= 1 {
				cType = parts[0]
				if len(parts) >= 2 {
					paramName = parts[1]
				} else {
					paramName = "p"
				}
			}
		} else {
			parts := strings.Fields(p)
			if len(parts) == 0 {
				continue
			}

			if len(parts) == 1 {
				cType = parts[0]
				if strings.HasSuffix(cType, "*") {
					isPtr = true
					cType = strings.TrimSuffix(cType, "*")
				}
				paramName = "p"
			} else if len(parts) == 2 {
				firstLooksLikeType := strings.HasSuffix(parts[0], "_t") ||
					parts[0] == "void" || parts[0] == "int" || parts[0] == "uint32" ||
					parts[0] == "uint64" || parts[0] == "uint16" || parts[0] == "uint8" ||
					parts[0] == "int32" || parts[0] == "size_t" || parts[0] == "unsafe.Pointer"

				if strings.HasSuffix(parts[0], "*") {
					isPtr = true
					cType = strings.TrimSuffix(parts[0], "*")
					paramName = parts[1]
				} else if strings.HasPrefix(parts[1], "*") {
					if firstLooksLikeType {
						cType = parts[0]
						paramName = strings.TrimPrefix(parts[1], "*")
						isPtr = true
					} else {
						paramName = parts[0]
						isPtr = true
						cType = strings.TrimPrefix(parts[1], "*")
					}
				} else if firstLooksLikeType {
					cType = parts[0]
					paramName = parts[1]
				} else {
					paramName = parts[0]
					cType = parts[1]
				}
			} else {
				starIdx := -1
				for i := 1; i < len(parts)-1; i++ {
					if parts[i] == "*" {
						starIdx = i
						isPtr = true
						break
					}
				}
				if starIdx > 0 {
					if starIdx == 1 && len(parts) == 3 {
						paramName = parts[0]
						cType = parts[2]
					} else {
						cType = parts[0]
						paramName = parts[starIdx+1]
					}
				} else {
					cType = parts[0]
					if strings.HasSuffix(cType, "*") {
						isPtr = true
						cType = strings.TrimSuffix(cType, "*")
					}
					paramName = parts[len(parts)-1]
					if strings.HasPrefix(paramName, "*") {
						isPtr = true
						paramName = strings.TrimPrefix(paramName, "*")
					}
				}
			}
		}

		goType := convertCTypeToGo(cType)
		if isPtr {
			if goType == "" || goType == "void" {
				goType = "unsafe.Pointer"
			} else {
				goType = "*" + goType
			}
		}

		goParams = append(goParams, fmt.Sprintf("%s %s", paramName, goType))
	}

	return strings.Join(goParams, ", ")
}

// convertCTypeToGo converts C type to Go type
func convertCTypeToGo(cType string) string {
	cType = strings.TrimSpace(cType)

	typeMap := map[string]string{
		"uintptr_t":      "uintptr",
		"uint32_t":       "uint32",
		"uint64_t":       "uint64",
		"uint16_t":       "uint16",
		"uint8_t":        "uint8",
		"int32_t":        "int32",
		"int":            "int",
		"void":           "",
		"byte":           "byte",
		"size_t":         "uint32",
		"unsafe.Pointer": "unsafe.Pointer",
	}

	if goType, ok := typeMap[cType]; ok {
		return goType
	}

	cTypeNoSuffix := strings.TrimSuffix(cType, "_t")
	if goType, ok := typeMap[cTypeNoSuffix]; ok {
		return goType
	}

	if cType == "uintptr" || cType == "uint32" || cType == "uint64" ||
		cType == "uint16" || cType == "uint8" || cType == "int32" ||
		cType == "int" || cType == "byte" || cType == "unsafe.Pointer" {
		return cType
	}

	return cType
}

// deduplicateSymbols removes duplicate symbol names, keeping the first occurrence
// This is needed during migration when symbols may exist in both GCC and Go assembly
func deduplicateSymbols(symbols []string) []string {
	seen := make(map[string]bool)
	var result []string
	for _, sym := range symbols {
		if !seen[sym] {
			seen[sym] = true
			result = append(result, sym)
		}
	}
	return result
}

// findGlobalSymbols scans GCC assembly files for .global symbols
func findGlobalSymbols(asmDir string) []string {
	var symbols []string
	globalRe := regexp.MustCompile(`^\.global\s+([a-zA-Z_][a-zA-Z0-9_.]*)`)

	filepath.Walk(asmDir, func(path string, info os.FileInfo, err error) error {
		if err != nil || !strings.HasSuffix(path, ".s") {
			return nil
		}

		content, err := ioutil.ReadFile(path)
		if err != nil {
			return nil
		}

		lines := strings.Split(string(content), "\n")
		for _, line := range lines {
			matches := globalRe.FindStringSubmatch(line)
			if len(matches) > 1 {
				symbols = append(symbols, matches[1])
			}
		}

		return nil
	})

	return symbols
}

// findGoAsmSymbols scans Go/Plan9 assembly files for TEXT directives
func findGoAsmSymbols(goasmDir string) []string {
	var symbols []string
	textRe := regexp.MustCompile(`^TEXT\s+·?([a-zA-Z_][a-zA-Z0-9_]*)\s*\(SB\)`)

	filepath.Walk(goasmDir, func(path string, info os.FileInfo, err error) error {
		if err != nil || !strings.HasSuffix(path, ".s") {
			return nil
		}

		content, err := ioutil.ReadFile(path)
		if err != nil {
			return nil
		}

		lines := strings.Split(string(content), "\n")
		for _, line := range lines {
			matches := textRe.FindStringSubmatch(line)
			if len(matches) > 1 {
				symbols = append(symbols, matches[1])
			}
		}

		return nil
	})

	return symbols
}

// parseGoAsmSignatures parses Go/Plan9 assembly files to extract function signatures
func parseGoAsmSignatures(goasmDir string) map[string]functionSignature {
	signatures := make(map[string]functionSignature)

	textRe := regexp.MustCompile(`^TEXT\s+·?([a-zA-Z_][a-zA-Z0-9_]*)\s*\(SB\)[^$]*\$(\d+)-(\d+)`)

	filepath.Walk(goasmDir, func(path string, info os.FileInfo, err error) error {
		if err != nil || !strings.HasSuffix(path, ".s") {
			return nil
		}

		content, err := ioutil.ReadFile(path)
		if err != nil {
			return nil
		}

		lines := strings.Split(string(content), "\n")
		for i, line := range lines {
			matches := textRe.FindStringSubmatch(line)
			if len(matches) >= 4 {
				funcName := matches[1]

				var params, returnType string

				for j := i - 1; j >= 0 && j >= i-10; j-- {
					prevLine := strings.TrimSpace(lines[j])
					if !strings.HasPrefix(prevLine, "//") {
						continue
					}

					// Match various comment formats:
					// - "// funcName(params) retType"
					// - "// funcName(params) returns retType"
					// - "// func funcName(params) retType"
					// The return type must be a valid Go type, not punctuation
					sigRe := regexp.MustCompile(`^//\s*(?:func\s+)?` + regexp.QuoteMeta(funcName) + `\s*\(([^)]*)\)\s*(?:returns\s+)?(uintptr|uint64|uint32|uint16|uint8|int64|int32|int|byte|bool|unsafe\.Pointer)?`)
					sigMatch := sigRe.FindStringSubmatch(prevLine)
					if len(sigMatch) >= 2 {
						params = strings.TrimSpace(sigMatch[1])
						if len(sigMatch) >= 3 && sigMatch[2] != "" {
							returnType = strings.TrimSpace(sigMatch[2])
						}
						break
					}

					// Only match "Returns: type" pattern (colon required to avoid matching prose)
					// This avoids false positives like "returns current value"
					retRe := regexp.MustCompile(`(?i)Returns:\s+(uintptr|uint64|uint32|uint16|uint8|int64|int32|int|byte|bool|unsafe\.Pointer)`)
					retMatch := retRe.FindStringSubmatch(prevLine)
					if len(retMatch) >= 2 && returnType == "" {
						returnType = strings.TrimSpace(retMatch[1])
					}
				}

				signatures[funcName] = functionSignature{
					params:     params,
					returnType: returnType,
				}
			}
		}

		return nil
	})

	return signatures
}
