//go:build ignore
// +build ignore

// Code generator for main.go dummy calls
// Scans assembly files to find Go functions called from assembly
// Generates dummy function calls to prevent dead code elimination
// Generates a complete Go file (no markers needed).
//
// Supports both:
//   - GCC assembly (.extern/.bl main.X in asm/aarch64/)
//   - Go/Plan9 assembly (BL main·X(SB) in asm/goasm/)
//
// Usage: go run generate-main-calls.go [-asm <dir>] [-goasm <dir>] [-go <dir>] [-o <path>]
//   -asm: GCC assembly source directory (default: asm/aarch64)
//   -goasm: Go/Plan9 assembly source directory (default: asm/goasm)
//   -go: Go source directory for signature discovery (default: main)
//   -o: Output Go file (default: stdout)

package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io"
	"io/ioutil"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

func main() {
	// Parse command line flags
	var outputFile string
	var asmDir string
	var goasmDir string
	var goSourceDir string
	flag.StringVar(&asmDir, "asm", "asm/aarch64", "GCC assembly source directory")
	flag.StringVar(&goasmDir, "goasm", "asm/goasm", "Go/Plan9 assembly source directory")
	flag.StringVar(&goSourceDir, "go", "main", "Go source directory for signature discovery")
	flag.StringVar(&outputFile, "o", "", "Output file (default: stdout)")
	flag.Parse()

	// Find all Go functions called from GCC assembly
	goFunctionsCalled := findGoFunctionsCalled(asmDir)

	// Find all Go functions called from Go/Plan9 assembly and merge
	goasmFunctions := findGoAsmFunctionsCalled(goasmDir)
	goFunctionsCalled = mergeFunctions(goFunctionsCalled, goasmFunctions)

	// Generate the complete file
	var generated strings.Builder
	generateCompleteFile(goFunctionsCalled, goSourceDir, &generated)

	// Format with gofmt
	formatted, err := formatWithGofmt(generated.String())
	if err != nil {
		fmt.Fprintf(os.Stderr, "Warning: gofmt failed, using unformatted output: %v\n", err)
		formatted = generated.String()
	}

	// Write output
	if outputFile == "" {
		// Write to stdout
		fmt.Print(formatted)
	} else {
		if err := ioutil.WriteFile(outputFile, []byte(formatted), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "Error writing to %s: %v\n", outputFile, err)
			os.Exit(1)
		}
		fmt.Fprintf(os.Stderr, "Generated %s\n", outputFile)
	}
}

// formatWithGofmt formats Go code using gofmt
func formatWithGofmt(code string) (string, error) {
	cmd := exec.Command("gofmt", "-s")
	cmd.Stdin = strings.NewReader(code)
	output, err := cmd.Output()
	if err != nil {
		return "", err
	}
	return string(output), nil
}

// mergeFunctions merges two function lists, removing duplicates
func mergeFunctions(a, b []string) []string {
	seen := make(map[string]bool)
	var result []string
	for _, f := range a {
		if !seen[f] {
			seen[f] = true
			result = append(result, f)
		}
	}
	for _, f := range b {
		if !seen[f] {
			seen[f] = true
			result = append(result, f)
		}
	}
	return result
}

// generateCompleteFile generates the complete main.go file
func generateCompleteFile(goFunctionsCalled []string, goSourceDir string, w io.Writer) {
	// Write file header
	fmt.Fprintln(w, "// Code generated by generate-main-calls.go. DO NOT EDIT.")
	fmt.Fprintln(w, "// Run 'make generate-main' to regenerate.")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "package main")
	fmt.Fprintln(w, "")

	// Generate the main function with dummy calls
	fmt.Fprintln(w, "// Dummy main() function required by Go's c-archive build mode")
	fmt.Fprintln(w, "// This is never called - boot.s calls KernelMain directly")
	fmt.Fprintln(w, "// We call functions here to ensure they're compiled and not optimized away")
	fmt.Fprintln(w, "func main() {")

	// Generate the function calls
	generateMainCallsContent(goFunctionsCalled, goSourceDir, w)

	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "\t// This should never execute in bare metal")
	fmt.Fprintln(w, "\tfor {")
	fmt.Fprintln(w, "\t}")
	fmt.Fprintln(w, "}")
}

// generateMainCallsContent generates dummy function calls for Go functions called from assembly
// Writes to the provided writer
func generateMainCallsContent(goFunctionsCalled []string, goSourceDir string, w io.Writer) {
	// Map of known function signatures (function name -> parameter types)
	knownSignatures := map[string][]string{
		"KernelMain":              {"uint32", "uint32", "uint32"},
		"UartTransmitHandler":     {},
		"kernelMainBodyWrapper":   {},
		"GrowStackForCurrent":     {},
		"ExceptionHandler":        {"uint64", "uint64", "uint64", "uint64", "uint32", "uint64", "uint64", "uint64"}, // (esr, elr, spsr, far, excType, savedSP, savedLR, savedG)
		"HandleSyscall":           {"uint64", "uint64", "uint64", "uint64", "uint64", "uint64", "uint64"},
		"fb_putc_irq":             {"byte"},                                                                         // Timer interrupt handler - print char to framebuffer
		"SyscallWriteBuffer":      {"unsafe.Pointer", "uint32"},                                                     // Syscall write handler - buffer to ring buffer
		"SyscallRead":             {"int32", "unsafe.Pointer", "uint64"},                                            // read syscall handler
		"SyscallClose":            {"int32"},                                                                        // close syscall handler
		"SyscallOpenat":           {"int32", "unsafe.Pointer", "int32", "int32"},                                    // openat syscall handler
		"SyscallSchedGetaffinity": {"int32", "uint64", "unsafe.Pointer"},                                            // sched_getaffinity syscall handler
		"SyscallFutex":            {"unsafe.Pointer", "int32", "uint32", "unsafe.Pointer", "unsafe.Pointer", "uint32"},
		"SyscallUnknown":          {"uint64"},                            // unknown syscall handler - print syscall number
		"timerSignal":             {},                                    // Timer signal handler
		"getRandomBytes":          {"unsafe.Pointer", "uint32"},          // getrandom syscall - fill buffer with random bytes
		"uartPutsDirect":          {"string"},                            // Direct UART string output
		"uartPutcDirect":          {"byte"},                              // Direct UART char output
		"uartPutHex32Direct":      {"uint32"},                            // Direct UART hex32 output
		"uartPutHex64Direct":      {"uint64"},                            // Direct UART hex64 output
	}

	// Parse Go source to find signatures for unknown functions
	for _, funcName := range goFunctionsCalled {
		if _, exists := knownSignatures[funcName]; !exists {
			sig, err := findFunctionSignature(goSourceDir, funcName)
			if err == nil && sig != nil {
				knownSignatures[funcName] = sig.Params
			} else {
				// Default to no parameters if we can't find it
				knownSignatures[funcName] = []string{}
			}
		}
	}

	// Group functions by category
	var kernelFunctions []string
	var interruptHandlers []string
	var otherFunctions []string

	for _, funcName := range goFunctionsCalled {
		if funcName == "KernelMain" {
			kernelFunctions = append(kernelFunctions, funcName)
		} else if strings.Contains(strings.ToLower(funcName), "handler") {
			interruptHandlers = append(interruptHandlers, funcName)
		} else {
			otherFunctions = append(otherFunctions, funcName)
		}
	}

	// Sort for consistent output
	sort.Strings(kernelFunctions)
	sort.Strings(interruptHandlers)
	sort.Strings(otherFunctions)

	// Generate kernel function calls
	if len(kernelFunctions) > 0 {
		fmt.Fprintf(w, "\t// Call kernel initialization functions to ensure they're compiled\n")
		fmt.Fprintf(w, "\t// This will never execute in bare metal, but ensures the functions exist\n")
		for _, funcName := range kernelFunctions {
			params := knownSignatures[funcName]
			call := generateFunctionCall(funcName, params)
			fmt.Fprintf(w, "\t%s\n", call)
		}
		fmt.Fprintf(w, "\n")
	}

	// Generate interrupt handler calls
	if len(interruptHandlers) > 0 {
		fmt.Fprintf(w, "\t// Reference interrupt handlers to prevent optimization\n")
		fmt.Fprintf(w, "\t// These are called from assembly interrupt handlers and must not be optimized away\n")
		for _, funcName := range interruptHandlers {
			params := knownSignatures[funcName]
			call := generateFunctionCall(funcName, params)
			fmt.Fprintf(w, "\t%s\n", call)
		}
		fmt.Fprintf(w, "\n")
	}

	// Generate other function calls
	if len(otherFunctions) > 0 {
		fmt.Fprintf(w, "\t// Reference other functions called from assembly\n")
		fmt.Fprintf(w, "\t// This will never execute in bare metal, but ensures the functions exist\n")
		for _, funcName := range otherFunctions {
			params := knownSignatures[funcName]
			call := generateFunctionCall(funcName, params)
			fmt.Fprintf(w, "\t%s\n", call)
		}
	}
}

// generateFunctionCall generates a function call string with appropriate dummy parameters
func generateFunctionCall(funcName string, paramTypes []string) string {
	if len(paramTypes) == 0 {
		return fmt.Sprintf("%s()", funcName)
	}

	var args []string
	for i, paramType := range paramTypes {
		arg := generateDummyArg(paramType, i)
		args = append(args, arg)
	}

	return fmt.Sprintf("%s(%s)", funcName, strings.Join(args, ", "))
}

// generateDummyArg generates a dummy argument value based on the parameter type
func generateDummyArg(paramType string, index int) string {
	// Remove pointer/array qualifiers for type matching
	baseType := strings.TrimLeft(paramType, "*[]")

	switch baseType {
	case "uint32", "uint", "uintptr":
		return "0"
	case "uint64":
		return "0"
	case "uint16":
		return "0"
	case "uint8", "byte":
		return "0"
	case "int32", "int":
		return "0"
	case "int64":
		return "0"
	case "bool":
		return "false"
	case "string":
		return `""`
	case "unsafe.Pointer":
		return "nil"
	default:
		// For unknown types, try nil or 0
		if strings.HasPrefix(paramType, "*") {
			return "nil"
		}
		return "0"
	}
}

// FunctionSignature represents a Go function's signature
type FunctionSignature struct {
	Name   string
	Params []string // Parameter types
}

// findFunctionSignature parses Go source files to find a function's signature
func findFunctionSignature(sourceDir string, funcName string) (*FunctionSignature, error) {
	fset := token.NewFileSet()

	// Parse all .go files in the directory
	pkgs, err := parser.ParseDir(fset, sourceDir, nil, parser.ParseComments)
	if err != nil {
		return nil, err
	}

	var foundSig *FunctionSignature

	for _, pkg := range pkgs {
		for _, file := range pkg.Files {
			ast.Inspect(file, func(n ast.Node) bool {
				fn, ok := n.(*ast.FuncDecl)
				if !ok {
					return true
				}

				if fn.Name == nil || fn.Name.Name != funcName {
					return true
				}

				// Found the function!
				sig := &FunctionSignature{
					Name: funcName,
				}

				if fn.Type.Params != nil {
					for _, param := range fn.Type.Params.List {
						paramType := exprToString(param.Type)
						// Handle multiple names for same type (e.g., "a, b int")
						numNames := len(param.Names)
						if numNames == 0 {
							numNames = 1 // Anonymous parameter
						}
						for i := 0; i < numNames; i++ {
							sig.Params = append(sig.Params, paramType)
						}
					}
				}

				foundSig = sig
				return false // Stop searching
			})

			if foundSig != nil {
				break
			}
		}
		if foundSig != nil {
			break
		}
	}

	if foundSig == nil {
		return nil, fmt.Errorf("function %s not found", funcName)
	}

	return foundSig, nil
}

// exprToString converts an ast.Expr to a string representation of the type
func exprToString(expr ast.Expr) string {
	switch e := expr.(type) {
	case *ast.Ident:
		return e.Name
	case *ast.SelectorExpr:
		return exprToString(e.X) + "." + e.Sel.Name
	case *ast.StarExpr:
		return "*" + exprToString(e.X)
	case *ast.ArrayType:
		return "[]" + exprToString(e.Elt)
	default:
		return "unknown"
	}
}

// findGoFunctionsCalled finds Go functions called from GCC assembly
func findGoFunctionsCalled(asmDir string) []string {
	var functions []string
	externRe := regexp.MustCompile(`\.extern\s+main\.([a-zA-Z_][a-zA-Z0-9_]*)`)
	blRe := regexp.MustCompile(`bl\s+main\.([a-zA-Z_][a-zA-Z0-9_]*)`)

	seen := make(map[string]bool)

	filepath.Walk(asmDir, func(path string, info os.FileInfo, err error) error {
		if err != nil || !strings.HasSuffix(path, ".s") {
			return nil
		}

		content, err := ioutil.ReadFile(path)
		if err != nil {
			return nil
		}

		lines := strings.Split(string(content), "\n")
		for _, line := range lines {
			// Skip comment-only lines (they might contain example code)
			trimmed := strings.TrimSpace(line)
			if strings.HasPrefix(trimmed, "//") && !strings.Contains(trimmed, ".extern") {
				continue
			}

			// Check for .extern declarations
			matches := externRe.FindStringSubmatch(line)
			if len(matches) > 1 && !seen[matches[1]] {
				functions = append(functions, matches[1])
				seen[matches[1]] = true
			}

			// Check for bl calls (but skip if it's in a comment)
			if !strings.HasPrefix(strings.TrimSpace(line), "//") {
				matches = blRe.FindStringSubmatch(line)
				if len(matches) > 1 && !seen[matches[1]] {
					functions = append(functions, matches[1])
					seen[matches[1]] = true
				}
			}
		}

		return nil
	})

	return functions
}

// findGoAsmFunctionsCalled finds Go functions and data symbols referenced from Go/Plan9 assembly
func findGoAsmFunctionsCalled(goasmDir string) []string {
	var functions []string
	// Match BL main·FuncName(SB) or CALL main·FuncName(SB)
	blRe := regexp.MustCompile(`(?:BL|CALL)\s+main·([a-zA-Z_][a-zA-Z0-9_]*)\(SB\)`)
	// Match MOVD $main·SymbolName(SB), Rxx - for data symbol references
	// When we find a data reference "foo", we'll look for "fooKeepAlive" function
	movdRe := regexp.MustCompile(`MOVD\s+\$main·([a-zA-Z_][a-zA-Z0-9_]*)\(SB\)`)

	seen := make(map[string]bool)

	filepath.Walk(goasmDir, func(path string, info os.FileInfo, err error) error {
		if err != nil || !strings.HasSuffix(path, ".s") {
			return nil
		}

		content, err := ioutil.ReadFile(path)
		if err != nil {
			return nil
		}

		lines := strings.Split(string(content), "\n")
		for _, line := range lines {
			// Skip comment-only lines
			trimmed := strings.TrimSpace(line)
			if strings.HasPrefix(trimmed, "//") {
				continue
			}

			// Check for BL/CALL to main.X
			matches := blRe.FindStringSubmatch(line)
			if len(matches) > 1 && !seen[matches[1]] {
				functions = append(functions, matches[1])
				seen[matches[1]] = true
			}

			// Check for MOVD $main.X(SB) - data symbol reference
			// Generate a KeepAlive function call for it
			movdMatches := movdRe.FindStringSubmatch(line)
			if len(movdMatches) > 1 {
				keepAliveName := movdMatches[1] + "KeepAlive"
				if !seen[keepAliveName] {
					functions = append(functions, keepAliveName)
					seen[keepAliveName] = true
				}
			}
		}

		return nil
	})

	return functions
}
