version: '3'

tasks:
  arm64:
    desc: Build clocks (interactor framework demo, ARM64)
    deps: [':check-env', ':mazarin:userspace-overlay', ':mancini:compile-constraints']
    sources:
      - 'flock/cmd/clocks/**/*'
      - 'mazarin/**/*.go'
      - '{{.USERSPACE_OVERLAY_JSON}}'
      - '{{.USERSPACE_OVERLAY_DIR}}/**/*'
    generates:
      - '{{.CLOCKS_ELF}}'
    cmds:
      - '{{.GO}} tool go-echo "Building clocks..."'
      - 'CGO_ENABLED=0 GOARCH={{.TARGET_GOARCH}} GOOS={{.TARGET_GOOS}} {{.GO}} build -overlay={{.ROOT_DIR}}/{{.USERSPACE_OVERLAY_JSON}} {{.GCFLAGS}} -o {{.CLOCKS_ELF}} ./flock/cmd/clocks'
      - '{{.GO}} tool go-echo "Clocks built at {{.CLOCKS_ELF}}"'

  x86_64:
    desc: Build clocks (x86_64)
    deps: [':check-env', ':mazarin:userspace-overlay', ':mancini:compile-constraints']
    sources:
      - 'flock/cmd/clocks/**/*'
      - 'mazarin/**/*.go'
      - '{{.USERSPACE_OVERLAY_JSON}}'
      - '{{.USERSPACE_OVERLAY_DIR}}/**/*'
    generates:
      - '{{.CLOCKS_AMD64_ELF}}'
    cmds:
      - '{{.GO}} tool go-echo "Building clocks for x86_64..."'
      - 'CGO_ENABLED=0 GOARCH=amd64 GOOS=linux {{.GO}} build -overlay={{.ROOT_DIR}}/{{.USERSPACE_OVERLAY_JSON}} {{.GCFLAGS}} -o {{.CLOCKS_AMD64_ELF}} ./flock/cmd/clocks'
      - '{{.GO}} tool go-echo "Clocks x86_64 built at {{.CLOCKS_AMD64_ELF}}"'

  riscv64:
    desc: Build clocks (RISC-V 64-bit)
    deps: [':check-env', ':mazarin:userspace-overlay', ':mancini:compile-constraints']
    sources:
      - 'flock/cmd/clocks/**/*'
      - 'mazarin/**/*.go'
      - '{{.USERSPACE_OVERLAY_JSON}}'
      - '{{.USERSPACE_OVERLAY_DIR}}/**/*'
    generates:
      - '{{.CLOCKS_RISCV64_ELF}}'
    cmds:
      - '{{.GO}} tool go-echo "Building clocks for RISC-V 64-bit..."'
      - 'CGO_ENABLED=0 GOARCH=riscv64 GOOS=linux {{.GO}} build -overlay={{.ROOT_DIR}}/{{.USERSPACE_OVERLAY_JSON}} {{.GCFLAGS}} -o {{.CLOCKS_RISCV64_ELF}} ./flock/cmd/clocks'
      - '{{.GO}} tool go-echo "Clocks RISC-V 64-bit built at {{.CLOCKS_RISCV64_ELF}}"'
