// DO NOT EDIT THIS FILE. It is generated by the build system.
package mazboot

import "unsafe"

//{{ LINKNAME START}}

// Link to external assembly functions from lib.s
//
//go:linkname mmio_write mmio_write
//go:nosplit
func mmio_write(reg uintptr, data uint32)

//go:linkname uart_init_pl011 uart_init_pl011
//go:nosplit
func uart_init_pl011()

//go:linkname uart_putc_pl011 uart_putc_pl011
//go:nosplit
func uart_putc_pl011(c byte)

//go:linkname mmio_read mmio_read
//go:nosplit
func mmio_read(reg uintptr) uint32

//go:linkname mmio_write16 mmio_write16
//go:nosplit
func mmio_write16(reg uintptr, data uint16)

//go:linkname mmio_read16 mmio_read16
//go:nosplit
func mmio_read16(reg uintptr) uint16

//go:linkname mmio_write64 mmio_write64
//go:nosplit
func mmio_write64(reg uintptr, data uint64)

//go:linkname delay delay
//go:nosplit
func delay(count int32)

//go:linkname busy_wait busy_wait
//go:nosplit
func busy_wait(count uint32)

//go:linkname systemstack runtime.systemstack
//go:nosplit
func systemstack(fn func())

//go:linkname bzero bzero
//go:nosplit
func bzero(ptr unsafe.Pointer, size uint32)

//go:linkname storePointerNoBarrier store_pointer_nobarrier
//go:nosplit
func storePointerNoBarrier(dest unsafe.Pointer, value unsafe.Pointer)

//go:linkname dsb dsb
//go:nosplit
func dsb()

//go:linkname isb isb
//go:nosplit
func isb()

//go:linkname qemu_exit qemu_exit
//go:nosplit
func qemu_exit()

//go:linkname get_stack_pointer get_stack_pointer
//go:nosplit
func get_stack_pointer() uintptr

//go:linkname get_caller_stack_pointer get_caller_stack_pointer
//go:nosplit
func get_caller_stack_pointer() uintptr

//go:linkname verifyStackPointerReading verify_stack_pointer_reading
//go:nosplit
func verifyStackPointerReading() int

//go:linkname set_g_pointer set_g_pointer
//go:nosplit
func set_g_pointer(g uintptr)

// System Control Register access functions for alignment diagnostics
//
//go:linkname read_sctlr_el1 read_sctlr_el1
//go:nosplit
func read_sctlr_el1() uint64

//go:linkname write_sctlr_el1 write_sctlr_el1
//go:nosplit
func write_sctlr_el1(value uint64)

//go:linkname disable_alignment_check disable_alignment_check
//go:nosplit
func disable_alignment_check()

//go:linkname switchToGoroutine switchToGoroutine
//go:nosplit
func switchToGoroutine(g *runtimeG, fn uintptr)

//{{ LINKNAME END}}
