// DO NOT EDIT THIS FILE. It is generated by the build system.
package mazboot

// Dummy main() function required by Go's c-archive build mode
// This is never called - boot.s calls KernelMain directly
// We call KernelMain here to ensure it's compiled and not optimized away
func main() {
	//{{ LINKNAME START}}
	// Call KernelMain with dummy values to ensure it's compiled
	// This will never execute in bare metal, but ensures the function exists
	KernelMain(0, 0, 0)

	// Reference interrupt handlers to prevent optimization
	// These are called from assembly interrupt handlers and must not be optimized away
	// This will never execute in bare metal, but ensures the functions exist
	ExceptionHandler(0, 0, 0, 0, 0)
	uartTransmitHandler() // UART TX interrupt handler

	// This should never execute in bare metal
	for {
	}
	//{{ LINKNAME END}}

}
