// Code generated by gen.go; DO NOT EDIT.

package bitfield

import (
	"fmt"
)

// UnpackPageFlags unpacks a uint32 into a PageFlags struct.
func UnpackPageFlags(packed uint32) PageFlags {
	var flags PageFlags
	flags.Allocated = (packed>>0)&0x1 != 0
	flags.KernelPage = (packed>>1)&0x1 != 0
	flags.Reserved = uint32((packed>>2)&0x3fffffff)
	return flags
}

// PackPageFlags packs a PageFlags struct into a uint32.
// This function explicitly ensures the result is 32 bits, even on 64-bit systems.
func PackPageFlags(flags PageFlags) (uint32, error) {
	packed, err := Pack(&flags, &Config{NumBits: 32})
	if err != nil {
		return 0, fmt.Errorf("PackPageFlags: %w", err)
	}
	// Explicitly mask to 32 bits to ensure we never exceed uint32 range
	// This is important on 64-bit systems where uint64 is the default
	result := uint32(packed & 0xFFFFFFFF)
	return result, nil
}
