// compile-constraints compiles .constraint source files into a Go source file
// containing *vm.Program literals. Each .constraint file contains one function
// in the restricted Go subset accepted by mazarin/vm/compile.
//
// Usage:
//
//	go tool compile-constraints -pkg interactor \
//	    -o mazarin/interactor/programs_gen.go \
//	    mazarin/interactor/constraints/*.constraint
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"mazzy/mazarin/vm"
	"mazzy/mazarin/vm/compile"
)

func main() {
	pkg := flag.String("pkg", "interactor", "package name for generated file")
	out := flag.String("o", "programs_gen.go", "output file path")
	flag.Parse()

	files := flag.Args()
	if len(files) == 0 {
		fmt.Fprintln(os.Stderr, "usage: compile-constraints -pkg PKG -o OUT file.constraint ...")
		os.Exit(1)
	}

	// Sort for deterministic output.
	sort.Strings(files)

	type entry struct {
		name string
		prog *vm.Program
	}
	var entries []entry

	for _, path := range files {
		src, err := os.ReadFile(path)
		if err != nil {
			fmt.Fprintf(os.Stderr, "read %s: %v\n", path, err)
			os.Exit(1)
		}

		result, err := compile.Compile(string(src))
		if err != nil {
			fmt.Fprintf(os.Stderr, "compile %s: %v\n", path, err)
			os.Exit(1)
		}

		// Derive variable name from filename: bounds_from_ulwh.constraint → ProgBoundsFromULWH
		base := filepath.Base(path)
		base = strings.TrimSuffix(base, ".constraint")
		varName := "Prog" + snakeToPascal(base)

		entries = append(entries, entry{name: varName, prog: result.Program})
	}

	var buf strings.Builder
	buf.WriteString("// Code generated by compile-constraints. DO NOT EDIT.\n")
	buf.WriteString("package " + *pkg + "\n\n")
	buf.WriteString("import \"mazzy/mazarin/vm\"\n\n")

	for _, e := range entries {
		emitProgram(&buf, e.name, e.prog)
		buf.WriteString("\n")
	}

	if err := os.WriteFile(*out, []byte(buf.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", *out, err)
		os.Exit(1)
	}
}

// snakeToPascal converts "bounds_from_ulwh" → "BoundsFromUlwh".
func snakeToPascal(s string) string {
	parts := strings.Split(s, "_")
	var buf strings.Builder
	for _, p := range parts {
		if len(p) == 0 {
			continue
		}
		buf.WriteString(strings.ToUpper(p[:1]))
		if len(p) > 1 {
			buf.WriteString(p[1:])
		}
	}
	return buf.String()
}

func emitProgram(buf *strings.Builder, name string, prog *vm.Program) {
	buf.WriteString("var " + name + " = &vm.Program{\n")

	// Code
	buf.WriteString("\tCode: []vm.Inst{\n")
	for _, inst := range prog.Code {
		buf.WriteString(fmt.Sprintf("\t\t{Opcode: 0x%02x, Typ: 0x%02x, Op1: %d, Op2: %d, Flags: %d, Imm: 0x%x},\n",
			inst.Opcode, inst.Typ, inst.Op1, inst.Op2, inst.Flags, inst.Imm))
	}
	buf.WriteString("\t},\n")

	// Strings
	buf.WriteString("\tStrings: []string{")
	if len(prog.Strings) > 0 {
		buf.WriteString("\n")
		for _, s := range prog.Strings {
			buf.WriteString(fmt.Sprintf("\t\t%q,\n", s))
		}
		buf.WriteString("\t")
	}
	buf.WriteString("},\n")

	// NumArgs
	buf.WriteString(fmt.Sprintf("\tNumArgs: %d,\n", prog.NumArgs))

	// ArgTypes
	buf.WriteString("\tArgTypes: []uint8{")
	for i, t := range prog.ArgTypes {
		if i > 0 {
			buf.WriteString(", ")
		}
		buf.WriteString(fmt.Sprintf("0x%02x", t))
	}
	buf.WriteString("},\n")

	// Funcs
	if len(prog.Funcs) > 0 {
		buf.WriteString("\tFuncs: []vm.FuncInfo{\n")
		for _, fi := range prog.Funcs {
			buf.WriteString(fmt.Sprintf("\t\t{Name: %q, PC: %d, NumArgs: %d, NumLocals: %d, LocalBase: %d},\n",
				fi.Name, fi.PC, fi.NumArgs, fi.NumLocals, fi.LocalBase))
		}
		buf.WriteString("\t},\n")
	}

	// Entry
	buf.WriteString(fmt.Sprintf("\tEntry: %d,\n", prog.Entry))

	buf.WriteString("}\n")
}
