// DO NOT EDIT THIS FILE. It is generated by the build system.
//
//go:generate go run ../../tools/generate-main-calls.go -asm ../../asm/aarch64 -file main.go -go .
package main

// Dummy main() function required by Go's c-archive build mode
// This is never called - boot.s calls KernelMain directly
// We call KernelMain here to ensure it's compiled and not optimized away
func main() {
	//{{ LINKNAME START}}
	//{{ LINKNAME END}}
	// This should never execute in bare metal
	for {
	}

}
