// DO NOT EDIT THIS FILE. It is generated by the build system.
//
//go:generate go run ../../tools/generate-main-calls.go -asm ../../asm/aarch64 -file main.go -go main
package main

// Dummy main() function required by Go's c-archive build mode
// This is never called - boot.s calls KernelMain directly
// We call KernelMain here to ensure it's compiled and not optimized away
func main() {
	//{{ LINKNAME START}}
	// Call kernel initialization functions to ensure they're compiled
	// This will never execute in bare metal, but ensures the functions exist
	KernelMain(0, 0, 0)

	// Reference interrupt handlers to prevent optimization
	// These are called from assembly interrupt handlers and must not be optimized away
	// This will never execute in bare metal, but ensures the functions exist
	ExceptionHandler(0, 0, 0, 0, 0)
	UartTransmitHandler() // UART TX interrupt handler

	// Reference other functions called from assembly
	// This will never execute in bare metal, but ensures the functions exist
	GrowStackForCurrent()
	kernelMainBodyWrapper()

	//{{ LINKNAME END}}
	// This should never execute in bare metal
	for {
	}

}
