// Code generated by compile-constraints from string_length.vgo. DO NOT EDIT.
package mancini

import "mazzy/mazarin/vm"

var ProgStringLength = &vm.Program{
	Code: []vm.Inst{
		{Opcode: 0x05, Typ: 0x00, Op1: 0, Op2: 0, Flags: 0, Imm: 0x0},
		{Opcode: 0x80, Typ: 0x00, Op1: 202, Op2: 1, Flags: 0, Imm: 0x0},
		{Opcode: 0x11, Typ: 0x00, Op1: 0, Op2: 0, Flags: 0, Imm: 0x0},
		{Opcode: 0x10, Typ: 0x00, Op1: 0, Op2: 0, Flags: 0, Imm: 0x0},
		{Opcode: 0x80, Typ: 0x00, Op1: 20, Op2: 1, Flags: 0, Imm: 0x0},
		{Opcode: 0x70, Typ: 0x00, Op1: 0, Op2: 1, Flags: 0, Imm: 0x0},
	},
	Strings: []string{
		"_source_",
	},
	NumArgs: 0,
	ArgTypes: []uint8{},
	Funcs: []vm.FuncInfo{
		{Name: "stringLength", PC: 0, NumArgs: 0, NumLocals: 1, LocalBase: 0},
	},
	Entry: 0,
}
