version: '3'

tasks:
  arm64:
    desc: Build linux shepherd (ARM64)
    deps: [':check-env', ':merged-shepherd-overlay']
    sources:
      - 'flock/**/*.go'
      - 'flock/**/*.s'
      - 'mazarin/**/*.go'
      - '{{.MERGED_SHEPHERD_OVERLAY_JSON}}'
      - '{{.USERSPACE_OVERLAY_DIR}}/**/*'
      - '{{.SHEPHERD_OVERLAY_DIR}}/**/*'
    generates:
      - '{{.LINUX_ELF}}'
    cmds:
      - '{{.GO}} tool go-echo "Building linux for ARM64..."'
      - 'CGO_ENABLED=0 GOARCH={{.TARGET_GOARCH}} GOOS={{.TARGET_GOOS}} {{.GO}} build -overlay={{.ROOT_DIR}}/{{.MERGED_SHEPHERD_OVERLAY_JSON}} {{.GCFLAGS}} -o {{.LINUX_ELF}} ./flock/cmd/linux'
      - '{{.GO}} tool go-echo "Stdio ARM64 built at {{.LINUX_ELF}}"'

  x86_64:
    desc: Build linux shepherd (x86_64)
    deps: [':check-env', ':merged-shepherd-overlay-amd64']
    sources:
      - 'flock/**/*.go'
      - 'flock/**/*.s'
      - 'mazarin/**/*.go'
      - '{{.MERGED_SHEPHERD_OVERLAY_AMD64_JSON}}'
      - '{{.USERSPACE_OVERLAY_DIR}}/**/*'
      - '{{.SHEPHERD_OVERLAY_AMD64_DIR}}/**/*'
    generates:
      - '{{.LINUX_AMD64_ELF}}'
    cmds:
      - '{{.GO}} tool go-echo "Building linux for x86_64..."'
      - 'CGO_ENABLED=0 GOARCH=amd64 GOOS=linux {{.GO}} build -overlay={{.ROOT_DIR}}/{{.MERGED_SHEPHERD_OVERLAY_AMD64_JSON}} {{.GCFLAGS}} -o {{.LINUX_AMD64_ELF}} ./flock/cmd/linux'
      - '{{.GO}} tool go-echo "Stdio x86_64 built at {{.LINUX_AMD64_ELF}}"'

  riscv64:
    desc: Build linux shepherd (RISC-V 64-bit)
    deps: [':check-env', ':merged-shepherd-overlay-riscv64']
    sources:
      - 'flock/**/*.go'
      - 'flock/**/*.s'
      - 'mazarin/**/*.go'
      - '{{.MERGED_SHEPHERD_OVERLAY_RISCV64_JSON}}'
      - '{{.USERSPACE_OVERLAY_DIR}}/**/*'
      - '{{.SHEPHERD_OVERLAY_RISCV64_DIR}}/**/*'
    generates:
      - '{{.LINUX_RISCV64_ELF}}'
    cmds:
      - '{{.GO}} tool go-echo "Building linux for RISC-V 64-bit..."'
      - 'CGO_ENABLED=0 GOARCH=riscv64 GOOS=linux {{.GO}} build -overlay={{.ROOT_DIR}}/{{.MERGED_SHEPHERD_OVERLAY_RISCV64_JSON}} {{.GCFLAGS}} -o {{.LINUX_RISCV64_ELF}} ./flock/cmd/linux'
      - '{{.GO}} tool go-echo "Stdio RISC-V 64-bit built at {{.LINUX_RISCV64_ELF}}"'
