//go:build !qemuvirt

// gen-runtime-stubs generates assembly overlay files that redirect runtime
// functions to priest's runtime.
//
// Usage: gen-runtime-stubs <priest.elf> <output-dir>
//
// This tool:
// 1. Reads priest.elf to find all runtime function addresses
// 2. Generates assembly files with stubs that jump to those addresses
// 3. Generates an overlay JSON file
//
// The generated stubs allow userspace programs to share priest's runtime,
// making them effectively goroutines within priest's scheduler.
package main

import (
	"bufio"
	"debug/elf"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// RuntimeFunc represents a runtime function to stub
type RuntimeFunc struct {
	Name       string
	PriestAddr uint64
	FrameSize  int // Stack frame size from symbol info, or 0 if unknown
}

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintf(os.Stderr, "Usage: %s <priest.elf> <output-dir>\n", os.Args[0])
		os.Exit(1)
	}

	priestPath := os.Args[1]
	outputDir := os.Args[2]

	// Find all runtime functions in priest
	functions, err := findRuntimeFunctions(priestPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading priest: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("Found %d runtime functions in priest\n", len(functions))

	// Create output directory
	if err := os.MkdirAll(outputDir, 0755); err != nil {
		fmt.Fprintf(os.Stderr, "Error creating output directory: %v\n", err)
		os.Exit(1)
	}

	// Generate assembly stubs
	stubFile := filepath.Join(outputDir, "runtime_stubs_arm64.s")
	if err := generateStubsFile(stubFile, functions); err != nil {
		fmt.Fprintf(os.Stderr, "Error generating stubs: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("Generated %s with %d stubs\n", stubFile, len(functions))

	// Generate a manifest for debugging
	manifestFile := filepath.Join(outputDir, "runtime_stubs.manifest")
	if err := generateManifest(manifestFile, functions); err != nil {
		fmt.Fprintf(os.Stderr, "Error generating manifest: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("\nNext steps:\n")
	fmt.Printf("1. Add the generated assembly file to the userspace overlay\n")
	fmt.Printf("2. Build userspace programs with the overlay\n")
}

// isRuntimeSymbol returns true if the symbol should be stubbed
func isRuntimeSymbol(name string) bool {
	// Include runtime.* and runtime/internal/*
	if !strings.HasPrefix(name, "runtime.") && !strings.HasPrefix(name, "runtime/internal/") {
		return false
	}

	// Exclude certain patterns that must remain local or are ABI-specific
	excludePatterns := []string{
		".abi0",              // ABI0 wrappers
		"systemstack_switch", // Must be local
		"mcall",              // Context switch - must be local
		"gogo",               // Context switch
		"gosave",             // Context switch
		"mstart",             // Thread start
		"rt0_go",             // Entry point
		"_rt0_",              // Entry points
		"asminit",            // Initialization
		"abort",              // Must be local
		"breakpoint",         // Debug
		"morestack",          // Stack growth - complex ABI
		"gcWriteBarrier",     // GC barrier - special handling
		"cgoSigtramp",        // CGO signal
		"sigtramp",           // Signal trampoline
		"asmcgocall",         // CGO
		"cgocall",            // CGO
		"racecall",           // Race detector
		"msanread",           // Memory sanitizer
		"msanwrite",
		"asanread",           // Address sanitizer
		"asanwrite",
	}

	for _, pattern := range excludePatterns {
		if strings.Contains(name, pattern) {
			return false
		}
	}

	return true
}

// findRuntimeFunctions finds all runtime functions in priest
func findRuntimeFunctions(path string) ([]RuntimeFunc, error) {
	f, err := elf.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	symbols, err := f.Symbols()
	if err != nil {
		return nil, err
	}

	var functions []RuntimeFunc
	for _, sym := range symbols {
		// Only include defined functions
		if elf.ST_TYPE(sym.Info) != elf.STT_FUNC || sym.Value == 0 {
			continue
		}
		if isRuntimeSymbol(sym.Name) {
			functions = append(functions, RuntimeFunc{
				Name:       sym.Name,
				PriestAddr: sym.Value,
			})
		}
	}

	// Sort by name for deterministic output
	sort.Slice(functions, func(i, j int) bool {
		return functions[i].Name < functions[j].Name
	})

	return functions, nil
}

// generateStubsFile generates the assembly file with all stubs
func generateStubsFile(path string, functions []RuntimeFunc) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	w := bufio.NewWriter(f)

	// Header
	fmt.Fprintln(w, "// Code generated by gen-runtime-stubs. DO NOT EDIT.")
	fmt.Fprintln(w, "// This file contains trampolines that redirect runtime functions to priest.")
	fmt.Fprintln(w, "//")
	fmt.Fprintln(w, "//go:build arm64")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#include \"go_asm.h\"")
	fmt.Fprintln(w, "#include \"textflag.h\"")
	fmt.Fprintln(w, "")

	// Generate each stub
	for _, fn := range functions {
		if err := generateStub(w, fn); err != nil {
			return fmt.Errorf("generating stub for %s: %w", fn.Name, err)
		}
	}

	return w.Flush()
}

// generateStub generates a single assembly stub
func generateStub(w *bufio.Writer, fn RuntimeFunc) error {
	// Convert Go name to assembly symbol
	// runtime.foo -> runtime·foo
	// runtime/internal/atomic.Load -> runtime∕internal∕atomic·Load
	asmName := goNameToAsm(fn.Name)

	// Generate stub
	// We use NOSPLIT because we're just trampolining, no stack growth needed
	// Frame size is 0 since we're just jumping
	fmt.Fprintf(w, "// %s -> 0x%x\n", fn.Name, fn.PriestAddr)
	fmt.Fprintf(w, "TEXT %s(SB), NOSPLIT|NOFRAME, $0\n", asmName)

	// Load the target address into R16 (IP0, a scratch register)
	// For addresses that fit in fewer bits, we could optimize, but
	// for simplicity we'll always use the full sequence
	addr := fn.PriestAddr

	// ARM64 immediate loading:
	// MOVZ loads 16 bits and zeros the rest
	// MOVK loads 16 bits and keeps the rest
	fmt.Fprintf(w, "\tMOVD $0x%x, R16\n", addr)
	fmt.Fprintf(w, "\tJMP (R16)\n")
	fmt.Fprintln(w, "")

	return nil
}

// goNameToAsm converts a Go symbol name to assembly syntax
func goNameToAsm(name string) string {
	// In Go assembly, the package name is separated from the symbol by · (middle dot)
	// The symbol itself (including method syntax) keeps its format
	//
	// Examples:
	//   runtime.mallocgc -> runtime·mallocgc
	//   runtime.(*Frames).Next -> runtime·(*Frames).Next
	//   runtime/internal/atomic.Load -> runtime∕internal∕atomic·Load

	// Find the first dot that separates the base package from the rest
	// For "runtime.foo" -> package="runtime", symbol="foo"
	// For "runtime.(*Foo).Bar" -> package="runtime", symbol="(*Foo).Bar"
	// For "runtime/internal/atomic.Load" -> package="runtime/internal/atomic", symbol="Load"

	// Split by the LAST dot to get package and symbol
	// But we need to handle method syntax like (*Foo).Bar

	// Find where the package path ends
	// The package path is everything up to the first identifier after the package
	// For methods, the first char after package. is '('

	var pkgEnd int
	for i := 0; i < len(name); i++ {
		if name[i] == '.' {
			// Check if this is the package separator
			// Package separator is followed by an identifier start char or '('
			if i+1 < len(name) {
				next := name[i+1]
				if next == '(' || (next >= 'A' && next <= 'Z') || (next >= 'a' && next <= 'z') || next == '_' {
					pkgEnd = i
					break
				}
			}
		}
	}

	if pkgEnd == 0 {
		return name
	}

	// Package path (with /)
	pkgPath := name[:pkgEnd]
	// Symbol (function or method)
	symbol := name[pkgEnd+1:]

	// Replace / with ∕ in package path
	pkgPath = strings.ReplaceAll(pkgPath, "/", "∕")

	// Combine with middle dot
	return pkgPath + "·" + symbol
}

// generateManifest generates a manifest file listing all stubbed functions
func generateManifest(path string, functions []RuntimeFunc) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	w := bufio.NewWriter(f)
	fmt.Fprintln(w, "# Runtime stubs manifest")
	fmt.Fprintln(w, "# Generated by gen-runtime-stubs")
	fmt.Fprintln(w, "#")
	fmt.Fprintf(w, "# Total functions: %d\n", len(functions))
	fmt.Fprintln(w, "#")
	fmt.Fprintln(w, "# Format: address name")
	fmt.Fprintln(w, "")

	for _, fn := range functions {
		fmt.Fprintf(w, "0x%08x %s\n", fn.PriestAddr, fn.Name)
	}

	return w.Flush()
}
