version: '3'

tasks:
  arm64:
    desc: Build clocks (interactor framework demo, ARM64)
    run: once
    deps: [':check-env', ':mazarin:userspace-overlay', ':mancini:compile-constraints']
    sources:
      - 'maz/clocks/**/*'
      - 'mazarin/**/*.go'
      - 'shared/**/*.go'
      - '{{.USERSPACE_OVERLAY_JSON}}'
      - '{{.USERSPACE_OVERLAY_DIR}}/**/*'
    generates:
      - '{{.CLOCKS_ELF}}'
    cmds:
      - '{{.GO}} tool go-echo "Building clocks..."'
      - 'CGO_ENABLED=0 GOARCH={{.TARGET_GOARCH}} GOOS={{.TARGET_GOOS}} {{.GO}} build -overlay={{.ROOT_DIR}}/{{.USERSPACE_OVERLAY_JSON}} {{.GCFLAGS}} -o {{.CLOCKS_ELF}} ./maz/clocks'
      - '{{.GO}} tool go-echo "Clocks built at {{.CLOCKS_ELF}}"'

  x86_64:
    desc: Build clocks (x86_64)
    run: once
    deps: [':check-env', ':mazarin:userspace-overlay', ':mancini:compile-constraints']
    sources:
      - 'maz/clocks/**/*'
      - 'mazarin/**/*.go'
      - 'shared/**/*.go'
      - '{{.USERSPACE_OVERLAY_JSON}}'
      - '{{.USERSPACE_OVERLAY_DIR}}/**/*'
    generates:
      - '{{.CLOCKS_AMD64_ELF}}'
    cmds:
      - '{{.GO}} tool go-echo "Building clocks for x86_64..."'
      - 'CGO_ENABLED=0 GOARCH=amd64 GOOS=linux {{.GO}} build -overlay={{.ROOT_DIR}}/{{.USERSPACE_OVERLAY_JSON}} {{.GCFLAGS}} -o {{.CLOCKS_AMD64_ELF}} ./maz/clocks'
      - '{{.GO}} tool go-echo "Clocks x86_64 built at {{.CLOCKS_AMD64_ELF}}"'

