// maz-reloc scans a .maz PIE ELF binary for call sites and data pointers
// that reference thin stub functions, and generates a .maz_imports section
// listing every reference that needs to be patched at load time.
//
// Usage: maz-reloc <binary.maz> <manifest>
//
// The manifest is the thin-stubs.manifest file generated by gen-ast-stubs,
// listing assembly symbol names of all stubbed functions.
//
// maz-reloc modifies the binary in-place, appending .maz_imports and
// .maz_import_strtab sections.
package main

import (
	"bufio"
	"bytes"
	"debug/elf"
	"encoding/binary"
	"fmt"
	"os"
	"strings"
)

// Relocation types for .maz_imports entries
const (
	RelocBL_ARM64  uint8 = 0 // ARM64 BL instruction (26-bit signed offset × 4)
	RelocCALL_X86  uint8 = 1 // x86_64 CALL instruction (E8 + 32-bit relative)
	RelocPTR64     uint8 = 2 // 8-byte absolute pointer (data sections)
	RelocJAL_RISCV uint8 = 3 // RISC-V JAL instruction (20-bit J-immediate × 2)
)

// importEntry is the on-disk format of a .maz_imports entry (16 bytes).
type importEntry struct {
	Offset    uint32 // offset from start of the segment containing this reference
	NameIdx   uint16 // index into string table
	RelocType uint8  // one of Reloc* constants
	Reserved  uint8
}

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintf(os.Stderr, "Usage: %s <binary.maz> <manifest>\n", os.Args[0])
		os.Exit(1)
	}

	mazPath := os.Args[1]
	manifestPath := os.Args[2]

	// Read the stub manifest (assembly symbol names, one per line)
	stubNames, err := readManifest(manifestPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading manifest: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("maz-reloc: loaded %d stub symbols from manifest\n", len(stubNames))

	// Open the ELF binary. Go's -T flag creates negative p_offset values
	// in program headers that debug/elf rejects. Use openELF which
	// sanitizes those before parsing.
	f, err := openELF(mazPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error opening ELF: %v\n", err)
		os.Exit(1)
	}
	defer f.Close()

	// Build a map of stub symbol name → address in the .maz binary
	stubAddrs := findStubAddresses(f, stubNames)
	if len(stubAddrs) == 0 {
		fmt.Printf("maz-reloc: no stub symbols found in binary, nothing to do\n")
		return
	}
	fmt.Printf("maz-reloc: found %d stub symbols in binary\n", len(stubAddrs))

	// Build reverse map: address → symbol name
	addrToName := make(map[uint64]string)
	for name, addr := range stubAddrs {
		addrToName[addr] = name
	}

	// Scan for references to stubs
	var imports []importRef

	// Scan .text for call instructions targeting stubs
	textImports := scanText(f, stubAddrs, addrToName)
	imports = append(imports, textImports...)

	// Scan data sections for pointer values matching stub addresses
	dataImports := scanDataSections(f, stubAddrs, addrToName)
	imports = append(imports, dataImports...)

	fmt.Printf("maz-reloc: found %d call sites + %d data pointers = %d total imports\n",
		len(textImports), len(dataImports), len(imports))

	if len(imports) == 0 {
		fmt.Printf("maz-reloc: no imports found, binary unchanged\n")
		return
	}

	// Build string table and import entries
	strtab, entries := buildImportSections(imports)

	// Append sections to the ELF binary
	if err := appendSections(mazPath, strtab, entries); err != nil {
		fmt.Fprintf(os.Stderr, "Error appending sections: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("maz-reloc: wrote %d imports (%d bytes) + strtab (%d bytes) to %s\n",
		len(entries), len(entries)*16, len(strtab), mazPath)
}

// openELF opens an ELF file, working around Go's -T flag which creates
// program headers with negative (huge) p_offset values that debug/elf rejects.
// We read the raw bytes, zero out any bogus phdr offsets, and parse from bytes.
func openELF(path string) (*elf.File, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	if len(data) < 64 || string(data[0:4]) != "\x7fELF" {
		return nil, fmt.Errorf("not an ELF file")
	}

	// ELF64: e_phoff at 0x20 (8 bytes), e_phentsize at 0x36 (2 bytes), e_phnum at 0x38 (2 bytes)
	phoff := binary.LittleEndian.Uint64(data[0x20:])
	phentsize := binary.LittleEndian.Uint16(data[0x36:])
	phnum := binary.LittleEndian.Uint16(data[0x38:])

	fileSize := uint64(len(data))
	for i := uint16(0); i < phnum; i++ {
		off := phoff + uint64(i)*uint64(phentsize)
		if off+uint64(phentsize) > fileSize {
			break
		}
		// p_offset is at bytes 8-15 within each phdr (ELF64)
		pOffset := binary.LittleEndian.Uint64(data[off+8:])
		if pOffset > fileSize {
			// Bogus offset (e.g. 0xffffffffffff1000 from -T flag) — zero it out.
			// maz-reloc only uses sections, not program headers, so this is safe.
			binary.LittleEndian.PutUint64(data[off+8:], 0)
		}
	}

	return elf.NewFile(bytes.NewReader(data))
}

// importRef is an in-memory representation of one import reference.
type importRef struct {
	fileOffset uint64 // offset within the ELF file where the reference is
	segOffset  uint32 // offset from the segment base VA
	name       string // symbol name to resolve
	relocType  uint8  // Reloc* constant
}

// readManifest reads the thin-stubs.manifest file and returns a set of symbol names.
func readManifest(path string) (map[string]bool, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	names := make(map[string]bool)
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		// Manifest uses middle dot (·), but ELF symtab uses regular dot (.)
		// Convert: runtime·mallocgc → runtime.mallocgc
		line = strings.ReplaceAll(line, "·", ".")
		names[line] = true
	}
	return names, scanner.Err()
}

// findStubAddresses looks up each stub symbol in the ELF's symbol table
// and returns a map of name → VA address for symbols that exist AND are
// actually thin stubs (not real functions from the userspace overlay).
// A thin stub is identified by its body: NOP followed by B self (ARM64),
// INT3+JMP self (x86_64), or NOP+J self (RISC-V).
func findStubAddresses(f *elf.File, stubNames map[string]bool) map[string]uint64 {
	result := make(map[string]uint64)

	syms, err := f.Symbols()
	if err != nil {
		return result
	}

	// Load .text section data for stub body verification
	text := f.Section(".text")
	var textData []byte
	var textAddr uint64
	if text != nil {
		textData, _ = text.Data()
		textAddr = text.Addr
	}

	skipped := 0
	for _, sym := range syms {
		if sym.Value == 0 || sym.Size == 0 {
			continue
		}
		if !stubNames[sym.Name] {
			continue
		}
		// Verify this is actually a thin stub by checking the function body.
		// The userspace overlay replaces some thin stubs with real functions
		// (e.g., syscall.RawSyscall6, syscall.Syscall6). We must not create
		// import entries for those — they have working implementations.
		isStub := textData != nil && isThinStub(f.Machine, textData, textAddr, sym.Value)
		if strings.Contains(sym.Name, "typeAssert") || strings.Contains(sym.Name, "interfaceSwitch") {
			fmt.Printf("maz-reloc: DEBUG %s addr=0x%X size=%d isStub=%v\n", sym.Name, sym.Value, sym.Size, isStub)
		}
		if isStub {
			result[sym.Name] = sym.Value
		} else if textData == nil {
			// Can't verify, include anyway
			result[sym.Name] = sym.Value
		} else {
			skipped++
		}
	}

	if skipped > 0 {
		fmt.Printf("maz-reloc: skipped %d manifest symbols (overlay-provided, not thin stubs)\n", skipped)
	}

	return result
}

// isThinStub checks if the function at the given VA starts with a thin stub pattern.
func isThinStub(machine elf.Machine, textData []byte, textAddr, funcAddr uint64) bool {
	offset := funcAddr - textAddr
	switch machine {
	case elf.EM_AARCH64:
		// ARM64 thin stub: NOP (0xD503201F) + B .-4 (0x17FFFFFF)
		// The B branches back to the NOP, creating an infinite loop.
		if offset+8 > uint64(len(textData)) {
			return false
		}
		insn0 := binary.LittleEndian.Uint32(textData[offset:])
		insn1 := binary.LittleEndian.Uint32(textData[offset+4:])
		return insn0 == 0xD503201F && insn1 == 0x17FFFFFF
	case elf.EM_X86_64:
		// x86_64 thin stub: INT3 (0xCC) + JMP self (0xEB 0xFE)
		if offset+3 > uint64(len(textData)) {
			return false
		}
		return textData[offset] == 0xCC && textData[offset+1] == 0xEB && textData[offset+2] == 0xFE
	case elf.EM_RISCV:
		// RISC-V thin stub: NOP (0x00000013) + J .-4 (0xffdff06f)
		// The J branches back to the NOP, creating a 2-instruction infinite loop.
		if offset+8 > uint64(len(textData)) {
			return false
		}
		insn0 := binary.LittleEndian.Uint32(textData[offset:])
		insn1 := binary.LittleEndian.Uint32(textData[offset+4:])
		return insn0 == 0x00000013 && insn1 == 0xffdff06f
	}
	return false
}

// scanText scans the .text section for call/branch instructions that target stub addresses.
func scanText(f *elf.File, stubAddrs map[string]uint64, addrToName map[uint64]string) []importRef {
	text := f.Section(".text")
	if text == nil {
		return nil
	}

	data, err := text.Data()
	if err != nil {
		return nil
	}

	var imports []importRef

	switch f.Machine {
	case elf.EM_AARCH64:
		imports = scanTextARM64(data, text.Addr, stubAddrs, addrToName)
	case elf.EM_X86_64:
		imports = scanTextX86_64(data, text.Addr, stubAddrs, addrToName)
	case elf.EM_RISCV:
		imports = scanTextRISCV64(data, text.Addr, stubAddrs, addrToName)
	}

	return imports
}

// scanTextARM64 scans ARM64 .text for BL instructions targeting stubs.
func scanTextARM64(data []byte, baseAddr uint64, stubAddrs map[string]uint64, addrToName map[uint64]string) []importRef {
	var imports []importRef

	for i := 0; i+3 < len(data); i += 4 {
		insn := binary.LittleEndian.Uint32(data[i:])

		// BL: bits [31:26] = 100101
		if insn&0xFC000000 != 0x94000000 {
			continue
		}

		// Decode 26-bit signed offset (in units of 4 bytes)
		imm26 := int32(insn & 0x03FFFFFF)
		if imm26&0x02000000 != 0 {
			imm26 |= ^int32(0x03FFFFFF) // sign extend
		}

		pc := baseAddr + uint64(i)
		target := uint64(int64(pc) + int64(imm26)*4)

		if name, ok := addrToName[target]; ok {
			if strings.Contains(name, "typeAssert") || strings.Contains(name, "interfaceSwitch") {
				fmt.Printf("maz-reloc: DEBUG BL at 0x%X -> %s (0x%X)\n", pc, name, target)
			}
			imports = append(imports, importRef{
				fileOffset: uint64(i), // offset in .text section data
				segOffset:  uint32(pc),
				name:       name,
				relocType:  RelocBL_ARM64,
			})
		}
	}

	return imports
}

// scanTextX86_64 scans x86_64 .text for CALL (E8) instructions targeting stubs.
func scanTextX86_64(data []byte, baseAddr uint64, stubAddrs map[string]uint64, addrToName map[uint64]string) []importRef {
	var imports []importRef

	for i := 0; i+4 < len(data); i++ {
		// CALL rel32: opcode E8
		if data[i] != 0xE8 {
			continue
		}

		// Decode 32-bit signed relative offset
		rel32 := int32(binary.LittleEndian.Uint32(data[i+1:]))
		pc := baseAddr + uint64(i)
		target := uint64(int64(pc) + 5 + int64(rel32))

		if name, ok := addrToName[target]; ok {
			imports = append(imports, importRef{
				fileOffset: uint64(i),
				segOffset:  uint32(pc),
				name:       name,
				relocType:  RelocCALL_X86,
			})
		}
	}

	return imports
}

// scanTextRISCV64 scans RISC-V .text for JAL instructions targeting stubs.
func scanTextRISCV64(data []byte, baseAddr uint64, stubAddrs map[string]uint64, addrToName map[uint64]string) []importRef {
	var imports []importRef

	for i := 0; i+3 < len(data); i += 2 { // RISC-V has 16-bit aligned instructions
		if i+3 >= len(data) {
			break
		}

		insn := binary.LittleEndian.Uint32(data[i:])

		// JAL rd, offset: opcode bits [6:0] = 1101111 (0x6F)
		// We only care about JAL ra (rd=1, i.e. function calls)
		if insn&0x7F != 0x6F {
			continue
		}

		// Check rd = x1 (ra) — bits [11:7]
		rd := (insn >> 7) & 0x1F
		if rd != 1 {
			continue
		}

		// Decode J-immediate: imm[20|10:1|11|19:12]
		imm20 := (insn >> 31) & 1
		imm10_1 := (insn >> 21) & 0x3FF
		imm11 := (insn >> 20) & 1
		imm19_12 := (insn >> 12) & 0xFF

		imm := (imm20 << 20) | (imm19_12 << 12) | (imm11 << 11) | (imm10_1 << 1)
		// Sign extend from bit 20
		if imm20 != 0 {
			imm |= 0xFFE00000
		}

		pc := baseAddr + uint64(i)
		target := uint64(int64(pc) + int64(int32(imm)))

		if name, ok := addrToName[target]; ok {
			imports = append(imports, importRef{
				fileOffset: uint64(i),
				segOffset:  uint32(pc),
				name:       name,
				relocType:  RelocJAL_RISCV,
			})
		}
	}

	return imports
}

// scanDataSections scans .data, .rodata, .noptrdata for 8-byte pointer values
// that match stub addresses.
func scanDataSections(f *elf.File, stubAddrs map[string]uint64, addrToName map[uint64]string) []importRef {
	var imports []importRef

	sectionNames := []string{".data", ".rodata", ".noptrdata", ".data.rel.ro"}
	for _, name := range sectionNames {
		sec := f.Section(name)
		if sec == nil {
			continue
		}

		data, err := sec.Data()
		if err != nil {
			continue
		}

		for i := 0; i+7 < len(data); i += 8 {
			val := binary.LittleEndian.Uint64(data[i:])
			if symName, ok := addrToName[val]; ok {
				va := sec.Addr + uint64(i)
				imports = append(imports, importRef{
					fileOffset: sec.Offset + uint64(i),
					segOffset:  uint32(va),
					name:       symName,
					relocType:  RelocPTR64,
				})
			}
		}
	}

	return imports
}

// buildImportSections builds the .maz_import_strtab and .maz_imports data.
func buildImportSections(imports []importRef) (strtab []byte, entries []importEntry) {
	// Build string table: deduplicate names
	nameToIdx := make(map[string]uint16)
	var strtabBuf []byte

	for _, imp := range imports {
		if _, exists := nameToIdx[imp.name]; !exists {
			nameToIdx[imp.name] = uint16(len(strtabBuf))
			strtabBuf = append(strtabBuf, []byte(imp.name)...)
			strtabBuf = append(strtabBuf, 0) // null terminator
		}
	}

	// Build import entries
	entries = make([]importEntry, len(imports))
	for i, imp := range imports {
		entries[i] = importEntry{
			Offset:    imp.segOffset,
			NameIdx:   nameToIdx[imp.name],
			RelocType: imp.relocType,
		}
	}

	return strtabBuf, entries
}

// appendSections appends .maz_imports and .maz_import_strtab sections to the ELF.
// This modifies the file in-place by:
// 1. Appending section data after the current end of file
// 2. Appending two new section headers
// 3. Updating the ELF header's section header count and string table
func appendSections(path string, strtab []byte, entries []importEntry) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("reading ELF: %w", err)
	}

	// Parse basic ELF header
	if len(data) < 64 {
		return fmt.Errorf("file too small for ELF header")
	}

	// Verify ELF magic
	if string(data[0:4]) != "\x7fELF" {
		return fmt.Errorf("not an ELF file")
	}

	// Read section header info from ELF header
	shoff := binary.LittleEndian.Uint64(data[0x28:])  // e_shoff
	shentsize := binary.LittleEndian.Uint16(data[0x3A:]) // e_shentsize
	shnum := binary.LittleEndian.Uint16(data[0x3C:])     // e_shnum
	shstrndx := binary.LittleEndian.Uint16(data[0x3E:])  // e_shstrndx

	if shoff == 0 || shnum == 0 {
		return fmt.Errorf("ELF has no section headers")
	}

	// Read the section header string table
	shstrOff := shoff + uint64(shstrndx)*uint64(shentsize)
	if shstrOff+uint64(shentsize) > uint64(len(data)) {
		return fmt.Errorf("section header string table out of bounds")
	}
	shstrShdr := data[shstrOff:]
	shstrDataOff := binary.LittleEndian.Uint64(shstrShdr[0x18:]) // sh_offset
	shstrDataSize := binary.LittleEndian.Uint64(shstrShdr[0x20:]) // sh_size

	// Current section header string table content
	shstrData := data[shstrDataOff : shstrDataOff+shstrDataSize]

	// New section names to add
	importsSectionName := ".maz_imports"
	strtabSectionName := ".maz_import_strtab"

	// Append new names to shstrtab
	newShstrStart := len(shstrData)
	importsNameOff := newShstrStart
	shstrData = append(shstrData, []byte(importsSectionName)...)
	shstrData = append(shstrData, 0)
	strtabNameOff := len(shstrData)
	shstrData = append(shstrData, []byte(strtabSectionName)...)
	shstrData = append(shstrData, 0)

	// Serialize import entries
	var importData []byte
	for _, e := range entries {
		var buf [16]byte
		binary.LittleEndian.PutUint32(buf[0:], e.Offset)
		binary.LittleEndian.PutUint16(buf[4:], e.NameIdx)
		buf[6] = e.RelocType
		buf[7] = e.Reserved
		// bytes 8-15 are padding (zero)
		importData = append(importData, buf[:]...)
	}

	// Plan the layout:
	// 1. Original file data (up to old section headers)
	// 2. New shstrtab data (extended)
	// 3. .maz_import_strtab data
	// 4. .maz_imports data
	// 5. New section headers (original + 2 new)

	// Determine where to place new data
	// We'll put everything after the end of the original file
	endOfFile := uint64(len(data))

	// New shstrtab location
	newShstrOff := endOfFile
	// Align to 8 bytes
	newShstrOff = (newShstrOff + 7) &^ 7

	// .maz_import_strtab location
	newImportStrtabOff := newShstrOff + uint64(len(shstrData))
	newImportStrtabOff = (newImportStrtabOff + 7) &^ 7

	// .maz_imports location
	newImportsOff := newImportStrtabOff + uint64(len(strtab))
	newImportsOff = (newImportsOff + 7) &^ 7

	// New section headers location
	newShoff := newImportsOff + uint64(len(importData))
	newShoff = (newShoff + 7) &^ 7

	// Build the output: start with original file data
	out := make([]byte, 0, int(newShoff)+int(shnum+2)*int(shentsize))
	out = append(out, data...)

	// Pad to newShstrOff
	for uint64(len(out)) < newShstrOff {
		out = append(out, 0)
	}
	// Write extended shstrtab
	out = append(out, shstrData...)

	// Pad to newImportStrtabOff
	for uint64(len(out)) < newImportStrtabOff {
		out = append(out, 0)
	}
	// Write .maz_import_strtab
	out = append(out, strtab...)

	// Pad to newImportsOff
	for uint64(len(out)) < newImportsOff {
		out = append(out, 0)
	}
	// Write .maz_imports
	out = append(out, importData...)

	// Pad to newShoff
	for uint64(len(out)) < newShoff {
		out = append(out, 0)
	}

	// Copy original section headers
	oldShData := data[shoff : shoff+uint64(shnum)*uint64(shentsize)]
	out = append(out, oldShData...)

	// Patch the copied shstrtab section header to point to new location/size
	shstrNewHeaderOff := uint64(len(out)) - uint64(shnum)*uint64(shentsize) + uint64(shstrndx)*uint64(shentsize)
	binary.LittleEndian.PutUint64(out[shstrNewHeaderOff+0x18:], newShstrOff)       // sh_offset
	binary.LittleEndian.PutUint64(out[shstrNewHeaderOff+0x20:], uint64(len(shstrData))) // sh_size

	// Append .maz_import_strtab section header
	var shdr [64]byte // ELF64 section header is 64 bytes
	binary.LittleEndian.PutUint32(shdr[0x00:], uint32(strtabNameOff)) // sh_name
	binary.LittleEndian.PutUint32(shdr[0x04:], 3)                     // sh_type = SHT_STRTAB
	binary.LittleEndian.PutUint64(shdr[0x18:], newImportStrtabOff)    // sh_offset
	binary.LittleEndian.PutUint64(shdr[0x20:], uint64(len(strtab)))   // sh_size
	binary.LittleEndian.PutUint64(shdr[0x30:], 1)                     // sh_addralign
	out = append(out, shdr[:shentsize]...)

	// Append .maz_imports section header
	var shdr2 [64]byte
	binary.LittleEndian.PutUint32(shdr2[0x00:], uint32(importsNameOff))     // sh_name
	binary.LittleEndian.PutUint32(shdr2[0x04:], 0x70000000)                 // sh_type = SHT_LOPROC (custom)
	binary.LittleEndian.PutUint64(shdr2[0x18:], newImportsOff)              // sh_offset
	binary.LittleEndian.PutUint64(shdr2[0x20:], uint64(len(importData)))    // sh_size
	binary.LittleEndian.PutUint64(shdr2[0x28:], uint64(shnum))              // sh_link = strtab section index
	binary.LittleEndian.PutUint64(shdr2[0x30:], 8)                          // sh_addralign
	binary.LittleEndian.PutUint64(shdr2[0x38:], 16)                         // sh_entsize = 16 bytes per entry
	out = append(out, shdr2[:shentsize]...)

	// Update ELF header
	binary.LittleEndian.PutUint64(out[0x28:], newShoff) // e_shoff
	binary.LittleEndian.PutUint16(out[0x3C:], shnum+2)  // e_shnum

	return os.WriteFile(path, out, 0755)
}
